{{econ821_header.txt}}
{{../markdown_header.txt}}


# Econ821: "Monetary Economics"

### [%ClassTerm]. Prof. Lutz Hendricks. UNC

-----------------

[Matlab and Programming][matlab]  |  [OLG model][olg]  |  [Wealth distribution][wealth]  |  [Economic Growth][growth]  |  [Cross-country income gaps][incomeGaps]

#Announcements #

<!---
* Student presentations start on Feb-17.
* Please sign up for presentations soon by emailing me.
--->

Feb-4: From next week onwards, the class will meet at 3:30 in Gardner 008.

As we go along, I will update the code (and data) for this class on [Github][githubLH]

The title is misleading. The course will focus on real macroeconomics. No money here.

In **preparation** for this class, I recommend:

1. install Matlab on your laptop (see my [Matlab Intro][])
2. familiarize yourself with Matlab
3. read something about good programming practices (see [Notes on programming])
4. start reading [QuantEcon](www.quant-econ.net)

Class meets Tu/Th 2-3:15pm in Gardner 007

Check this web site (www.lhendricks.org) regularly for updates.


# Organization

###Objectives
1. Learn about state of the art research in selected areas of macro.
2. Learn how to compute models and take them to the data.
3. Identify potential topics for dissertation research. [See my notes on finding research topics.](../Research/DissertationTips.htm)


###We cover the following broad topics:
1. Economic growth
2. Cross-country income gaps
3. Within country income / wealth inequality. 


###Class structure
A mixture of lectures, [student presentations][studPresent], and hands-on programming.

The lectures present key papers in each topic.

We will then replicate the results of select papers using **Matlab**.

This class is somewhat experimental. We will have to figure out how to efficiently do programming in class as we go along. Suggestions are welcome.


###Grading

The class is graded based on participation in class.

Students are expected to present and discuss state-of-the art papers on the topics we will cover.

---------


# Outline #

## Matlab and Programming [matlab] ##

Jan-12 to 21: The material for this section is hosted at [ReadTheDocs](http://matlab-introduction.readthedocs.org/en/latest/index.html)

## Solving heterogeneous agent OLG models [olg] ##

Jan-26: [Partial equilibrium](olg2d/olg_2period_sl.pdf) (these are slides presented in class)

* [General equilibrium](olg2d/olg_2period_ge_sl.pdf)
* The code for this lives in the `olg2d` folder on [Github][githubLH].

Jan-28: [Stochastic model](olg2d/olg_2s_sl.pdf)

Feb-2: [Many period stochastic model](olg2d/olg_mult_sl.pdf)

Feb-4: [Computing the multi-period model](olg2d/olg_mult2_sl.pdf)


## Wealth Distribution [wealth] ##

Feb-9: [Background lecture](wealth/wealth_sl.pdf)

* [Bequests](wealth/wealth_bequ_sl.pdf)

Feb-11: [Entrepreneurship](wealth/wealth_selfempl_sl.pdf)

* [Other extensions](wealth/wealth_other_sl.pdf)

Feb-16: Student presentations ([notes on their format](student_presentations.html))

* David: Cozzi
* Deepak: Boserum

Feb-18: Student presentations

* Andrew: de Nardi (2016)

## Redistribution #

Feb-23: [Redistribution I](wealth/income_distribution_sl.pdf)

Feb-25: [Redistribution II](wealth/income_distribution2_sl.pdf)

## Economic Growth [growth] ##

[Growth facts](growth/growth_facts_sl.pdf)

[Replicating growth facts / data sources](http://data-sources.readthedocs.org/en/latest/)

## Cross-Country Income Differences [incomeGaps] ##

[Background on cross-country income gaps](growth/cc_income_gaps_sl.pdf)

### Human Capital ###

[Human capital quality](growth/hc_sl.pdf)

Presentation and discussion of current papers (by students).

### Misallocation ###

[Misallocation](growth/misallocation_sl.pdf)

### End of Class ###

[Matlab Intro]: http://matlab-introduction.readthedocs.org/en/latest/matlab_intro.html)

[Notes on programming]: http://matlab-introduction.readthedocs.org/en/latest/programming.html

[githubLH]: https://github.com/hendri54/Econ821

[studPresent]: student_presentations.html

