{{../../markdown_header.txt}}

# Finding and Advisor #

You should aim to meet with **3-4 potential advisors** during the first 3 weeks of classes.

First, pick a **broad topic**, such as income inequality, monetary policy, health, ...

Then look for faculty members with expertise in this area. UNC Econ faculty is listed [here](http://econ.unc.edu/people/faculty/) with their fields of interest. The following is a rough classification:

* Microeconomic theory (Biglaiser, Norman, Parreiras, Li, Yates, Woodward)
* Macroeconomics (Aguilar, Francis, Alder, Parke, Rabinovic, Tian)
* International economics (Conway, Chari, Alder, Rosefielde)
* Econometrics (Babii, Verdier)
* Financial/Time-series econometrics (Ghysels, Hill, Aguilar, Hansen)
* Microeconometrics (Guilkey, Kim, Verdier)
* Labor/education economics (Flabbi, Fruehwirth, Hincapie, Peter, Turchi)
* Health economics (Gilleskie, Gong, Guilkey, Hincapie, Maini)
* Industrial organization (Maini, McManus, Williams)
* Environmental economics (Yates)
* Development economics (Peter-micro; Conway and Alder-macro)

The advisor must be permanent of adjunct faculty in the Department of Economics.

The following faculty are *not* available to advise in the Fall of 2018: Chari, Francis, Peter, Verdier.

Look at potential faculty members' web sites for their working papers and publications. You are looking for someone with an active research agenda.

Schedule appointments with a few potential advisors. 

**Prepare**. Think about potential topics and questions of interest. The more specific you can be, the better.

In your meetings, be concise and precise. Listen. 

Do not get discouraged when an advisor "shoots down" your topic. This is normal. Most project ideas are bad. This remains true, even for people who have many years of research experience. See the notes on [finding a topic](finding_topic.html).

----------------