{{../../markdown_header.txt}}

# Finding a Topic: Examples

## Immigrant wage gains

"Human Capital and Development Accounting: New Evidence From Immigrant Earnings", with Todd Schoellman

**Question**: How important is human capital for cross-country income differences?

**Literature**:

1. Measure human capital using years of schooling.

	Problems: 
	
	1. a year of schooling in Ghana is not the same as a year of schooling in the U.S.
	2. human capital is more than schooling

2. Model how human capital is produced.

	Problems:
	
	1. inputs and outputs of human capital production not observed
	2. results differ widely across studies

3. Immigrant earnings.

	Problems: immigrants are selected.
	
**Idea**: 

1. Build on the immigrant earnings idea: observe workers from the same country at home and in the U.S.
2. Address the selection problem by observing the same *person* in both countries (wage gains at migration).

Data: New Immigrant Survey


## Returns to Experience ##

"Accounting for Changing Returns to Experience"

**Question**: Age-wage profiles have changed over time (changing returns to experience). Why?

**Literature**:

1. Large descriptive literature does not directly address causality.
2. Various theoretical mechanisms:
	1. Changing occupational mobility
	2. Human capital accumulation on the job + rising college entry
	3. Changing return to skill versus raw labor

**Idea**:

1. Think of wage = efficiency * skill price
2. The literature tries to construct models where age efficiency profiles change over time and skill prices are more or less constant over time.
3. But we have reasons to believe that skill prices change substantially over time (separate literature).
4. What if we try this the other way around: hold age efficiency profiles constant and let skill prices vary over time?

**Approach**:

A very parsimonious model (that's the whole point) where

1. skill prices are a function of relative labor supplies (Katz & Murphy)
2. age efficiency profiles are simply exogenous and constant over time
3. cohort effects (intercepts of age profiles) depend on cohort schooling


## Return to College ##

"The Return to College: Selection and Dropout Risk," with Oksana Leukhina

**Question**: 

* College graduates earn about 60% more than high school graduates. 
* How much of that premium is selection? How much is return to college?

Main challenge: **selection**

* College graduates are "smarter" / higher ability than high school graduates.
* Need to remove that selection effect from return to college.

**Literature**: Too massive to summarize

1. Mincer returns: regress log wages on schooling and controls
	Problems: selection confounds results.
	
2. IV

	Problems:

	1. Hard to find instruments.
	2. Each instrument hits a different treatment group.
	3. IV returns to college are *lower* than OLS returns -- hard to interpret.

3. Structural models of school choice

	Problems: 

	1. Identification is hard without a good measure of ability.
	2. What happens in college is typically a black box.

**Idea**: College transcripts 

1. Transcripts offer information about student abilities.
2. Can observe how students progress through college. Can model incentives to persist or drop out.

Approach: Structural model that models in detail how students progress through college.

## Past Theses

### "Intergenerational Mobility and the Persistence of Shocks to Educational Attainment" by Jimmy Chin

* Question: How much intergenerational income persistence is there in China?
* Contribution: **Better data** applied to a known question.
	* also **better measurement** of permanent income (possible with better data)
* Contribution: Use historical events (Great Famine, Cultural Revolution) as **natural experiments** that shock parental education. Examine their effect on children's outcomes. (This is the best part of the paper.)
* The opening: better data.

### "Is Geopolitical Risk Priced?" by Lucas McCallen

* Question: Does geopolitical risk affect stock prices?
* Geopolitical risk: "risk associated with wars, terrorist acts, and tensions between states;" measured by an index from the literature.
* Contribution: Ask whether geopolitical risk affects prices after controlling for other "Fama-French" factors. (Answer: no)
* The opening: combine new "data" (the index of geopolitical risk) with an old question (Fama-French).

### "The Impact of State-Level Abortion Restrictions on Female Labor Supply" by Ben Roberts

* Question: see title
* Contribution: apply a known technique to newer data (recent abortion policies as instruments).
* Result: not a valid instrument.
* Regrouping: estimate a hazard model of first births to capture effect on timing of births.
* Now abortion restrictions significantly reduce labor supply.
* The opening: straightforward application of a known method to newer data.

### "Measuring Central Bank Transparency" by Katie Rha

* Question: Does central bank "transparency" alter the effects of monetary policy actions?
* Contribution: use text scraping to create a measure of transparency
	* basic idea: how "similar" are internal Fed discussions and external Fed communication?
* The opening: new tools (text scraping) applied to an old question.

## Take-Away Messages ##

1. Each project has a clearly defined, specific question.
2. In most cases, the question is not new.
3. The motivation for each project: a shortcoming in the existing literature. But you need to be constructive and have an idea how to do better.

### Project Opportunities ###

1. New data (New Immigrant Survey, college transcripts).
2. New observations from known data
	1. Example: Returns to experience are higher in richer countries (Lagakos et al., 2017, JPE).
3. Better identification (college transcripts help to measure student abilities).
4. A new mechanism to explain a known observation
	1. But need supporting evidence for the mechanism.
	2. Example: Test scores of college students rise over time relative to high school graduates. Suggests that selection accounts for rising college premium (Hendricks & Schoellman, 2014 JME).
5. A new question (rare)

---------------