{{../../markdown_header.txt}}

# Finding a Topic #

It is hard to overstate how **important** it is to find a good topic. It is crucial, essential, make or break. So spend time on it.

A good topic poses a **specific question**. If you cannot state your topic as a question, you are in trouble.

* A good topic: "What fraction of cross-country income variation is due to human capital?"
* A bad topic: "What are the effects of more schooling on a country's outcomes?" 
	* This is too broad (effects on what?).
	* This is too vague (how does the "more schooling" come about?).
* A very bad topic: "I explore the implications of banking regulations in Europe."

How to find a specific question? Start with a **broad area** that interests you. This should be narrower than a field (narrower than "monetary economics", for example), but broader than a specific question (such as "What are the effects of Quantitative Easing on long-term bond yields?"). More like: "Unconventional monetary policy" or "College dropouts" or "the role of institutions for cross-country income differences".

In order to narrow this down to a specific question, you need to **read a lot**. 

* Start with surveys (Journal of Economic Perspectives, Journal of Economic Literature, Handbooks in Economics). See [writing a literature review](lit_review.html) for more help on finding references.
* Don't read papers in detail at this stage. You want to get the big picture.

You need to **understand the literature** before you can identify a topic. 

* You need to know what questions have been answered. What do experts agree and disagree on?
* You need to understand appropriate methods and datasets.
* This is why a [literature review](lit_review.html) is one of your first tasks.

Key points:

* Most topics are bad (too hard, not doable, already done, too vague, not interesting). *Expect to go through 10 candidate topics before you find a good one*.
* Talk to people who know what they are doing early on; before you spend too much time on a bad topic.
* It is fine to ask potential advisors to suggest topics.


## Links ##

* [Summaries of how I found topics for my own research](finding_topic_examples.html)
* [Summaries of past theses](material/past_theses_summary.pdf)
* [Potential ideas for topics](topics.html)
* You may find my notes on [finding dissertation topics](../teaching/dissertation_tips.html) useful, even though this is written for PhD students.
* This document draws on [Tips from Harvard University](http://economics.harvard.edu/files/economics/files/thesislogistics17-18.pdf)

---------