{{../markdown_header.txt}}

# How to Read Papers Effectively #

While you read, keep these questions in mind (due to Lee Ohanian):

1. What is the question?
2. What is the approach?
3. Why is the approach reasonable?
4. What are the results?
5. How does the paper change the way I think about economics?

Skip the details

* Unless you have to, focus on the big picture and skip implementation details.
* Example: Acemoglu, Johnson & Robinson
	* you may want to remember that the paper uses settler mortality as an instrument for institutions.
	* you don't need to read in detail how the data are constructed, what controls are used in the regressions, etc.
* If you need to pass judgement on the paper (do I find the results compelling?), then you need to sweat the details

Take notes.

* While you read, make a structured bibliography in your favorite (outline capable) writing tool.

------------------