{{../../markdown_header.txt}}

# Preparing for Econ691H during the summer

It is a good idea to get a head start on the thesis process. If you have time during the summer, use it!

General notes:

1. [Read a couple of theses](../links.html#pastTheses) to get an idea of what is expected.
2. Read journal articles in areas you find interesting in order to expand your thesis topic ideas.
3. Talk to potential advisors to narrow down your topic. I can point you in the right direction.
	4. See [finding an advisor](finding_advisor.html) for more info and a list of economics faculty members by field.
4. Pick a software package and learn it.
	5. See the [FAQ](../honors_faq.html) for info on software.
6. A lot of theses ask cause-effect questions. Review methods for estimating causal effects: instrumental variables, natural experiments.

If you have a reasonably specific topic in mind, talk to me. I can point you to potential advisors and help you to refine the topic.

-----------