{{../markdown_header.txt}}

# Constructing a theoretical model

A model is a simplified version of reality. Everything that is not needed to make the desired argument is deleted from reality.

A model has standard ingredients that need to be described:

1. Demographics: what agents are in the model (households, firms, ...). How do they enter the model (births)? How do they exit (deaths)? 
2. Preferences: economic agents maximize something. What do they maximize?
3. Endowments: what do the agents have when the world starts? What do they have in each period (e.g. one unit of time to spend working).
4. Constraints:
	1. households and firms face budget constraints
	2. they may be additional constraints, such as borrowing limits
4. Markets: what can be traded? How are markets organized?
5. Information structure: who knows what and when?

With all this information, you can write down each agent's constrained optimization problem. 

## What Is a Good Model? ##

1. A good model is as simple as can be. Anything in the model needs to be motivated. Why is it needed to make the argument?
2. A good model is no simpler than needed. If there is a serious concern that omitting something will affect the conclusions, this needs to be defended.
3. Assumptions should be clear and their motivation must be explained.

## Other points ##

1.	Make sure you describe clearly which parts of the model are borrowed from the literature.-------------