{{../markdown_header.txt}}

# Writing a Thesis or Proposal #

Remember to **back up** your files (with versioning!). Every semester, I have at least one student who is late for a submission because his computer "crashed." There is no excuse for this any more. Your files should be continuously backed up to the cloud (and regularly to a local drive).

## Structure ##

A typical structure for an empirical paper would be

1. Introduction
2. Literature review (see [separate notes](lit_review.html))
3. Empirical approach
4. Data and variable construction
5. Results
6. Conclusion

## General Rules ##

1. Aim for short sentences and short paragraphs.
2. The paper should have enough visual structure that a reader can skim it and still get the outline of what is going on.
3. Use an equation editor for math (or better: use Latex, which is made easy by using [Lyx](lyx.org)).
4. Do not report numbers with lots of decimal places.

## Introduction ##

The Intro is the roadmap to your paper. It should tell the reader:

1. What is the question?
2. Why is it important?
3. How is it approached?
4. Why is the approach reasonable?
5. What are the results?
6. What is the contribution relative to the literature?

Things to do or avoid:

1. State the question clearly and right away. Avoid many paragraphs of text leading up to the question. Questions end with question marks.

## Formatting

1. Figures should be inserted in a vector format (e.g., PDF), not a raster format (e.g., JPG, PNG). Raster formats do not scale well.
2. Tables:
	3. No pasted STATA output.
	4. Add a table note that briefly explains how to read the table.
	5. Define abbreviations and symbols.

----------------