{{markdown_header.txt}}

## Computer Code

My [github repo](https://github.com/hendri54) contains code for recent projects.

The [shared repo](https://github.com/hendri54/shared) contains general purpose code.


Making this code available is a small attempt at reducing duplication, given that [economics lacks a code archive](thoughts/duplication.html).

Feel free to use my code in your research (with attribution, where appropriate).

Related material:

* General notes on [programming and Matlab][Matlab Intro]
* Replication code for [Manuelli and Seshadri, "Human Capital and the Wealth of Nations", AER 2014](https://github.com/hendri54/ms2014) (Their original code as published on the AER web site contains a substantial error. The authors have confirmed this to me.)


## External Links ##

[Chris Carroll's notes on dynamic programming](http://www.econ2.jhu.edu/people/ccarroll/SolvingMicroDSOPs/)

----------


[Matlab Intro]: http://matlab-introduction.readthedocs.org/en/latest/matlab_intro.html
