{{markdown_header.txt}}

{{contact_info.txt}}

## Research #

[Research on human capital](Research/research.html)  |  [Research on other topics](Research/research_other.html) | [C.V.](Research/CV_LutzHendricks.pdf)

[Computer code](computer_code.html)

## Teaching Spring 2019

Office hours: Tue, Thr, 2-3pm

[Econ692H](honors/econ692h.html): Honors Seminar

If you wish to apply for the **2019/20 honors seminar**, information is posted [here](honors/intro.html).

## Teaching Fall 2018 

[Econ720](econ720/econ720.html): Advanced Macro Theory I (PhD)

[Econ691H](honors/econ691h.html): Honors Seminar

[Teaching related notes](teaching/teaching.html)

[Tips for PhD students](teaching/phd_students.html)


## Thoughts ##

2017-July: [Economists need to specialize](thoughts/specialization.html)

[How economists can avoid reinventing the wheel](thoughts/duplication.html)

[On simple models calibrated using little data](thoughts/quantitative_models.html)

[Models and beliefs](thoughts/models_beliefs.html)

[Micro versus macro models](thoughts/micro_macro.html)

I do **not** have openings for research positions at any level.

This is my professional web site. Personal content is posted elsewhere.

-----------