{{markdown_header.txt}}

{{contact_info.txt}}

## Research #

[Research on human capital](Research/research.html)  |  [Research on other topics](Research/research_other.html) | [C.V.](Research/CV_LutzHendricks.pdf)

[Computer code](computer_code.html)

[Teaching related notes](teaching/teaching.html)

[Tips for PhD students](teaching/phd_students.html)

## Teaching Fall 2017 ##

Office hours: Tue, Thr 2:30-3:30pm

[Econ720](econ720/econ720.html): Advanced Macro Theory I (PhD)

[Econ691H](honors/econ691h.html): Honors Seminar

## Teaching Spring 2017 ##

[Econ520](econ520/econ520.html): Advanced Macroeconomic Theory

[Econ920](econ920/econ920.html): Dissertation Workshop (PhD)


## Thoughts ##

2017-July: [Economists need to specialize](thoughts/specialization.html)

[How economists can avoid reinventing the wheel](thoughts/duplication.html)

[On simple models calibrated using little data](thoughts/quantitative_models.html)

[Models and beliefs](thoughts/models_beliefs.html)

[Micro versus macro models](thoughts/micro_macro.html)

I do **not** have openings for research positions at any level.

This is my professional web site. Personal content is posted elsewhere.

-----------