{{markdown_header.txt}}

# Tips for Writing a PaperSeparate the presentation of what you do from the discussion of why you do it. Brief comments mixed in with the model presentation are ok. Long discussions make it hard to follow what you actually do.Separate the presentation of the model from the derivation of its implications. It is very confusing to read a paper that mixes assumptions with results. First present the model. Define equilibrium. Then derive properties of the equilibrium.There is a standard structure for presenting a model:1. Demographics
2. Endowments3. Preferences4. Technologies
5. Market arrangements
Only once these have been stated is it acceptable to talk about equilibrium properties or agents' problems. Next, describe the agents' problems, and define an equilibrium.For some exceptionally well written papers, take a look at the work of Richard Rogerson.