{{../markdown_header.txt}}

[Wealth Distribution][]  |  [Other Topics][]

#Wealth Distribution

###Retirement wealth and lifetime earnings

[International Economic Review](http://onlinelibrary.wiley.com/doi/10.1111/j.1468-2354.2007.00433.x/full), 2007, 48(2): 421-56.

[Bibtex citation](published/Bibtex2007IER.html)

###How Important Is Discount Rate Heterogeneity for Wealth Inequality?

[Journal of Economic Dynamics & Control](http://www.sciencedirect.com/science/article/pii/S0165188906002004), 2007, 31(9): 3042-68.

[Bibtex citation](published/Bibtex2007JEDC.html)

###Intended and Accidental Bequests in a Life-cycle Economy

This paper studies quantitative importance of accidental versus intended bequests. The main finding is that accidental bequests account for at least half, and perhaps for all of observed bequests.  

[Paper](wps/ab_paper.pdf) [First draft: August 2001]

###Bequests and Retirement Wealth in U.S. Data

This is a background paper for “Intended and Accidental Bequests in a Life-cycle Economy.” It documents bequests and retirement wealth in the SCF and the PSID. 

[Paper](wps/bequdata_paper.pdf)  |  [Tables](wps/BequData_Tables.pdf)

------------------------------------------------------------------------

# Other Topics #

### Accounting for Changing Returns to Experience [experience] ###

[BEJM][], forthcoming.

Proposes a simple model with time-invariant age-efficiency profiles to account for changing returns to experience in CPS data.

[Paper](experience/paper_quartic.pdf)  |  [Bibtex citation](experience/bibtexExperience.html)  |  [Code and additional results](https://github.com/hendri54/experience-quartic)

### Constructing Age-Earnings Profiles From CPS Data [cpsearn] ###

Describes procedures for constructing age-wage profiles from March CPS data.

Intended as documentation for the data used in several of my projects.

The code is available on [github](https://github.com/hendri54/cps-profiles).

[Paper](https://github.com/hendri54/cps-profiles/blob/master/paper_cpsearn.pdf)  |  [Bibtex entry](wps/bibtex_cpsearn.txt)

###Validation of IPUMS International Industry and Education Data

This document collects validation information for selected samples of the IPUMS International dataset. The focus is on industry and education data.  

[Paper](published/validation_ipumsi.pdf) (2010-Feb)
 
### The Intergenerational Persistence of Lifetime Earnings ###

[European Economic Review](https://www.journals.elsevier.com/european-economic-review), 2007, 51: 125-44.

-------------

[BEJM]: https://www.degruyter.com/view/j/bejm