{{../markdown_header.txt}}

# Research: Human Capital #

## Current working papers

### Family Background, Academic Ability, and College Decisions in the 20th Century U.S. [borrow_constraints] ###

With [Chris Herrington][] and [Todd Schoellman][] | [Slides](borrowing/hendricks.pdf) | [Bibtex entry](borrowing/bibtex.html)

### [Human Capital and Development Accounting: New Evidence From Immigrant Earnings](nis/newimmigrants2.pdf) [nis_migrants] ###

2016-Mar. With [Todd Schoellman][] | [Bibtex entry](nis/bibtex_nis.txt)

### [The Return to College: Selection and Dropout Risk](risky/paper_rs.pdf) [RiskySchool]

2016-May-9. With [Oksana Leukhina][] | [Online Appendix](risky/online_appendix.pdf) | [Bibtex citation](risky/BibtexRisky.html)  

### [Accounting for the Evolution of U.S. Wage Inequality](soin/paper_soin.pdf) [soin]

2013-May-10. [Bibtex citation](soin/BibtexSoin.html)  
 
## Publications ##

### [How Risky Is College Investment?](http://www.sciencedirect.com/science/article/pii/S1094202517300406) [gradpred] ###

With [Oksana Leukhina][] | Forthcoming, [Review of Economic Dynamics][] | [Bibtex citation](gradpred/bibtex_gp.html)

### [Student Abilities During the Expansion of U.S. Education](http://www.sciencedirect.com/science/article/pii/S0304393214000208) [ability]

With [Todd Schoellman][]. [Journal of Monetary Economics][], 36: 19-36, 2014.  
[Appendix](ability/paper_abil_app.pdf). 
[Bibtex citation](ability/BibtexAbility.html)
  
### [Cross-country Variation in Educational Attainment: Structural Change or Within Industry Skill Upgrading?](http://link.springer.com/article/10.1007/s10887-010-9055-9) [hdind]

[Journal of Economic Growth][] 15(3), 2010.
[Bibtex citation](published/BibtexJEG2010.html). 

[IPUMS Validation paper](validation_ipumsi.pdf).  
[Mapping from country specific to detailed industries](published/ind_mapping_hdind.out).

### [The Skill Composition of U.S. Cities](http://onlinelibrary.wiley.com/doi/10.1111/j.1468-2354.2010.00617.x/full) [hc_cities] ###

[International Economic Review][IER] 52(1): 1-32, 2011. 
[Bibtex citation](published/BibtexCitiesIER.html)

Previous title: Educational attainment in U.S. cities. 

### Taxation and Human Capital Accumulation

[Macroeconomic Dynamics](http://wueconb.wustl.edu/%7Ebarnett/MD.html) 2004, 8(3) 

[Paper](http://journals.cambridge.org/abstract_S1365100504030123). 
[Bibtex citation](published/Bibtex2004MD.html)

### Taxation and the Intergenerational Transmission of Human Capital

[Journal of Economics Dynamics and Control](http://www.elsevier.nl/homepage/sae/econbase/dyncon/) 2003, 27(9): 1639-1662. 

[Paper](http://www.sciencedirect.com/science/article/pii/S016518890200074X). [Bibtex citation](published/Bibtex2003JEDC.html)

### [How Important is Human Capital for Development? Evidence from Immigrant Earnings](http://www.jstor.org/stable/10.2307/3083328)

[American Economic Review][AER] 2002, 92(1): 198-219. 
[Bibtex citation](published/Bibtex%20AER%202002.html). 

[Technical Appendix](published/mhc_tech.pdf). 
[Data table](published/mhc_data_table.xls) with Mincer regressions and other source country data (MS Excel format).  
  
### How Do Taxes Affect Human Capital? The Role of Intergenerational Mobility [hctax]

[Review of Economic Dynamics](http://www.sciencedirect.com/science/article/pii/S1094202501901310) 2001, 4(3): 695-735.  

[Technical Appendix](published/hctax_tech_appx.pdf) | 
[Bibtex citation](published/Bibtex2001RED.html)  
   
### Growth, Death, and Taxes [gdtax]

[Review of Economic Dynamics](http://www.sciencedirect.com/science/article/pii/S1094202500901194)  2001, 4(1): 26-57. 

[Bibtex citation](published/Bibtex2001RED2.html)

### Taxation and Long-Run Growth

[Journal of Monetary Economics](http://www.sciencedirect.com/science/article/pii/S0304393298000580), 1999, (43)2: 411-434. 

[Bibtex citation](published/Bibtex1999JME.html)  
The [Technical Appendix](published/wp96_2_appx.pdf) contains details on computation and analytics.  
Program files are available in the following zip files:

* [Main](published/grtax_programs.zip) program files
* [Shared](published/grtax_shared.zip) program files


## Older working papers

### [The Ben-Porath Model and Age-wage Profiles](ojttech/paper_otech.pdf) [ojttech]

2012-Nov-27. [Bibtex citation](ojttech/bibtex.html)  

### [The Evolution of U.S. Wages: Skill Prices versus Human Capital](sojt/paper_sojt.pdf)

2012-Feb-23.  [Bibtex citation](sojt/BibtexSojt.html)

###Why Does Education Differ Across Countries? [scd_paper]

[Paper](wps/sdc_paper.pdf) (First draft: March 2005). [Bibtex citation](wps/BibtexEdCountries.html)


## Discussions ##

[MisMatch in Human Capital Accumulation](discussions/cooper_discussion_sl.pdf)

------------

[AER]: http://www.aeaweb.org/aer
[IER]: http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291468-2354
[Journal of Economic Growth]: http://www.springer.com/economics/growth/journal/10887
[Journal of Monetary Economics]: http://www.elsevier.nl/inca/homepage/sae/econbase/monec/
[Review of Economic Dynamics]: https://www.journals.elsevier.com/review-of-economic-dynamics
[Oksana Leukhina]: http://faculty.washington.edu/oml/
[Todd Schoellman]: https://sites.google.com/site/toddschoellman/
[Chris Herrington]: https://sites.google.com/site/cmherrington/home