{{../markdown_header.txt}}

# Research: Human Capital #

### Family Background, Academic Ability, and College Decisions in the 20th Century U.S. [borrow_constraints] ###

With Christopher Herrington and [Todd Schoellman][]. [Slides](borrowing/nber2015_sl.pdf). [Bibtex entry](borrowing/bibtex.html)

### Human Capital and Development Accounting: New Evidence From Immigrant Earnings [nis_migrants] ###

With [Todd Schoellman][]. [Slides](nis/cireq_sl.pdf)

### How Risky Is College Investment? [gradpred] ###

with [Oksana Leukhina][]. [Paper 2015-Jan-23](gradpred/paper_gp.pdf)
[Slides](gradpred/concordia_sl.pdf)
[Bibtex citation](gradpred/bibtex_gp.html)

### Accounting for the Evolution of U.S. Wage Inequality [soin]

[Paper 2013-May-10](soin/paper_soin.pdf) [Bibtex citation](soin/BibtexSoin.html)  
  
### The Ben-Porath Model and Age-wage Profiles [ojttech]

[Paper 2012-Nov-27](ojttech/paper_otech.pdf) [Bibtex citation](ojttech/bibtex.html)  

### The Evolution of U.S. Wages: Skill Prices versus Human Capital

[Paper 2012-Feb-23](sojt/paper_sojt.pdf) [Bibtex citation](sojt/BibtexSojt.html)
  
### The Return to College: Selection and Dropout Risk [RiskySchool]

With [Oksana Leukhina][]. [Paper 2014-Nov-1](risky/paper_rs.pdf) [Bibtex citation](risky/BibtexRisky.html)  

### Student Abilities During the Expansion of U.S. Education [ability]

[Journal of Monetary Economics](http://www.sciencedirect.com/science/article/pii/S0304393214000208), 36: 19-36, 2014.  
 With [Todd Schoellman][]. [Appendix](ability/paper_abil_app.pdf) [Bibtex citation](ability/BibtexAbility.html)
  
### Cross-country Variation in Educational Attainment: Structural Change or Within Industry Skill Upgrading? [hdind]

[Journal of Economic Growth](http://www.springerlink.com/openurl.asp?genre=article&id=doi:10.1007/s10887-010-9055-9&sa_campaign=Email/ACE/Paginated) 15(3), 2010.

[Paper](http://link.springer.com/article/10.1007/s10887-010-9055-9) - 
[IPUMS Validation paper](validation_ipumsi.pdf) - 
[Mapping from country specific to detailed industries](published/ind_mapping_hdind.out) - 
[Bibtex citation](published/BibtexJEG2010.html)

### The Skill Composition of U.S. Cities [hc_cities] ###

[International Economic Review](http://onlinelibrary.wiley.com/journal/10.1111/%28ISSN%291468-2354) 52(1): 1-32, 2011.

Previous title: Educational attainment in U.S. cities. 
[Paper](http://onlinelibrary.wiley.com/doi/10.1111/j.1468-2354.2010.00617.x/full) 
[Bibtex citation](published/BibtexCitiesIER.html)

###Why Does Education Differ Across Countries? [scd_paper]

[Paper](wps/sdc_paper.pdf) (First draft: March 2005) [Bibtex citation](wps/BibtexEdCountries.html)


###Taxation and Human Capital Accumulation

[Macroeconomic Dynamics](http://wueconb.wustl.edu/%7Ebarnett/MD.html) 2004, 8(3) 

[Paper](http://journals.cambridge.org/abstract_S1365100504030123)
[Bibtex citation](published/Bibtex2004MD.html)

### Taxation and the Intergenerational Transmission of Human Capital

[Journal of Economics Dynamics and Control](http://www.elsevier.nl/homepage/sae/econbase/dyncon/) 2003, 27(9): 1639-1662. 

[Paper](http://www.sciencedirect.com/science/article/pii/S016518890200074X) [Bibtex citation](published/Bibtex2003JEDC.html)

### How Important is Human Capital for Development? Evidence from Immigrant Earnings

[American Economic Review](http://www.jstor.org/stable/10.2307/3083328) 2002, 92(1): 198-219. 

[Bibtex citation](published/Bibtex%20AER%202002.html) | 
[Technical Appendix](published/mhc_tech.pdf)

[Data table](published/mhc_data_table.xls) with Mincer regressions and other source country data (MS Excel format).  
  
### How Do Taxes Affect Human Capital? The Role of Intergenerational Mobility [hctax]

[Review of Economic Dynamics](http://www.sciencedirect.com/science/article/pii/S1094202501901310) 2001, 4(3): 695-735.  

[Technical Appendix](published/hctax_tech_appx.pdf) | 
[Bibtex citation](published/Bibtex2001RED.html)  
   
###Growth, Death, and Taxes [gdtax]

[Review of Economic Dynamics](http://www.sciencedirect.com/science/article/pii/S1094202500901194)  2001, 4(1): 26-57. 

[Bibtex citation](published/Bibtex2001RED2.html)

### Taxation and Long-Run Growth

[Journal of Monetary Economics](http://www.sciencedirect.com/science/article/pii/S0304393298000580), 1999, (43)2: 411-434. 

[Bibtex citation](published/Bibtex1999JME.html)  
The [Technical Appendix](published/wp96_2_appx.pdf) contains details on computation and analytics.  
Program files are available in the following zip files:

* [Main](published/grtax_programs.zip) program files
* [Shared](published/grtax_shared.zip) program files


###Why Does Educational Attainment Differ Across U.S. States? [educAttain]

[Paper](hcd/hcd_paper.pdf) [Version: September 2004] [First draft: November 2003]
[Bibtex citation]


[American Economic Review]: http://www.aeaweb.org/aer
[Journal of Monetary Economics]: http://www.elsevier.nl/inca/homepage/sae/econbase/monec/
[Review of Economic Dynamics]: http://www.apnet.com/www/journal/rd.htm
[Oksana Leukhina]: http://faculty.washington.edu/oml/
[Todd Schoellman]: https://sites.google.com/site/toddschoellman/