{{../markdown_header.txt}}

# Econ520 - Advanced Macroeconomic Theory #

## Spring 2017 - Prof. Lutz Hendricks ###

## Announcements

* The final exam date is Fri, May 5, at noon (in the usual class room)
* Important: you must have passed Intermediate Macroeconomics to register for this course.
* Slides will be updated as the course progresses.


### Links ####

[Syllabus](syllabus520.html) | [Math review problems](Math_RQ.pdf) |  [Tips for taking exams](../teaching/exam_tips.html)

--------------------------------------

# Schedule
	
[Economic growth][] - [Short run][] - [Medium run][] - [Open economy][] - [Expectations][]

{{schedule520.mmd}} 

[inactive]: ../inactive_link.html