{{../markdown_header.txt}}

# Econ520 - Advanced Macroeconomic Theory #

## Spring 2016 - Prof. Lutz Hendricks ###

## Announcements

* Mar-1: I posted [answers for the midterm](exams/exam1_520_2016spring.pdf)
* Feb-4: It is time to start thinking about the [term paper](term_paper.html)
* Important: you must have passed Intermediate Macroeconomics to register for this course.
* Slides will be updated as the course progresses.

For those planning / buying ahead: the texts will be

 * Charles Jones. Introduction to Economic Growth, 3rd edition, 2013, ISBN-13: 978-0393919172.
	 * The 2002 2nd edition is on reserve in the library. (Call number HD75 .J66 2002 c. 2). It is very similar to the 3rd edition.
 * Olivier Blanchard. Macroeconomics (6th ed.). Prentice Hall. 2012. ISBN-13: 978-0133061635 
	 * The 2010 edition is on reserve (Call number HB172.5 .B573 2010)
 * Older editions of both books are ok and could be a lot less expensive.

Class meets 12:30-1:45 in Gardner 106.

Check this web site ([www.lhendricks.org](www.lhendricks.org)) regularly for updates.

### Links ####

[Syllabus](syllabus520.html) | [Math review problems](Math_RQ.pdf) |  [Tips for taking exams](../teaching/exam_tips.html)

--------------------------------------

# Schedule
	
[Economic growth][] - [Short run][] - [Medium run][] - [Open economy][] - [Expectations][] - [Past exams][]

## Economic Growth [Economic Growth] #

Jan-12 (Tue): [Growth facts](growth/GrowthFacts_SL.pdf)

* In case you need a refresher: [Growth rates and logarithms](growth/growth_algebra_sl.pdf), [PP](growth/growth_algebra_rq.pdf) (practice problems; previous exams are at the bottom of the page)

Jan-14 (Thr): [Methods for identifying causes and effects](growth/causes_SL.pdf)

Jan-19 (Tue): [The Role of Capital](growth/Capital_SL.pdf), [PP](growth/Capital_RQ.pdf)

Jan-21 (Thr): [Solow model](growth/Solow_SL.pdf), [PP](growth/Solow_RQ.pdf)  

Jan-28 (Thr): [Solow Applications](growth/Solow_Applications_SL.pdf)

* [Part 2](growth/Solow_Applications2_SL.pdf)

Feb-2 (Tue): [Institutions](growth/Institutions_SL.pdf), [PP](growth/Institutions_RQ.pdf)

Feb-4 (Thr): [Growth and ideas](growth/Ideas_SL.pdf)

Feb-9 (Tue): [Romer model](growth/RandD_SL.pdf), [PP](growth/RandD_RQ.pdf)

Feb-16 (Tue): Digression: [Rising income inequality](inequality/Inequality_SL.pdf)

## Short Run #

Feb-18 (Thr): [IS-LM model](islm/islm_sl.pdf)

Feb-23 (Tue): [Equilibrium](islm/islm_equil_sl.pdf), [PP](islm/islm_rq.pdf)

## Medium Run #

Feb-25 (Thr): [Labor market](asad/labor_mk_sl.pdf), [PP](asad/Labor_RQ.pdf)

<!--- 
[Rising wage inequality](asad/labor_inequality_sl.pdf)
enable next time; take material out of inequality_sl
--->

Mar-1(Tue): Midterm

Mar-3 (Thr): [AS-AD model](asad/asad_model_sl.pdf), [PP](asad/as_ad_rq.pdf) (covers Phillips Curve)

Mar-8 (Tue): [Inflation and unemployment](asad/infl_unempl_sl.pdf)

Mar-10 (Thr): [Inflation expectations and monetary policy](expectations/expectations_sl.pdf), [PP](expectations/expectations_rq.pdf)

Mar-15 to 17: Spring break

<!---
* European Unemployment: [SL](asad/EuropeUnemployment_SL.pdf), [PP](asad/EuropeUnemployment_RQ.pdf)
* The Financial Crisis: [SL](crisis/crisis_sl.pdf), [PP](crisis/Crisis_RQ.pdf))
--->

## Open Economy #

<!---
Mar-22: Exchange rates: [SL](open/basics_open_sl.pdf)
--->

Mar-22: [Trade deficits](open/TradeDeficit_SL.pdf), [PP](open/TradeDeficit_RQ.pdf)

Mar-31: IS-LM model: [SL](open/islm_open_sl.pdf), [PP](open/is_lm_open_rq.pdf)

Apr-5: AS-AD model: [SL](open/asad_open_sl.pdf), [PP](open/as_ad_open_rq.pdf)

## Expectations #

Apr-12: Asset prices: [SL](expectations/asset_prices_sl.pdf), [PP](expectations/asset_prices_rq.pdf)

Apr-14: Consumption and investment: [SL](expectations/consumption_sl.pdf), [PP](expectations/consumption_rq.pdf)

Apr-19: Expectations and policy: [SL](expectations/policy_sl.pdf), [PP](expectations/policy_rq.pdf)

Apr-21: Fiscal policy: [SL](policy/fiscal_sl.pdf), [PP](policy/fiscal_rq.pdf)

Apr-26: Model synthesis: [SL](expectations/model_summary_sl.pdf)

<!---
The recovery post 2008

* [Secular stagnation?](crisis/secular_stagnation_sl.pdf)
* [Slow wage growth][inactive]
--->

[International trade](open/trade_sl.pdf)

Apr-26: Last class: Review. All questions answered.

##Final exam: TBA

* Rules as previou exam. 
* Material covered: TBA
* But remember: New material builds on older material.

-----------------------------

#Past exams #

(material in early years differs substantially from current year):

* 2016 Spring: [Midterm](exams/exam1_520_2016spring.pdf)
* 2015 Spring: [exam1](exams/exam1_520_2015spring.pdf), [exam2](exams/exam2_520_2015spring.pdf), [final](exams/exam3_520_2015spring.pdf)
* 2013 Fall: [exam1](exams/exam1_520_2013fall.pdf), [exam2](exams/exam2_520_2013fall.pdf), [final](exams/exam3_520_2013fall.pdf).
* 2012 Fall: [exam1](exams/exam1_520_2012fall.pdf), [exam2](exams/exam2_520_2012fall.pdf), [final](exams/exam3_520_2012fall.pdf).
* 2012 Spring: [exam1](exams/exam1_520_s2012.pdf), [exam2](exams/exam2_520_s2012.pdf), [final](exams/exam3_520_s2012.pdf).
* 2010 (course title was Econ499): [exam1](exams/exam1_499_s2011.pdf), [exam2](exams/exam2_499_s2011.pdf), [final](exams/exam3_499_s2011.pdf).


If you want to read about current economic issues:

* [baselinescenario.com](baselinescenario.com) by Simon Johnson and James Kwak

[growthFacts]: growth/GrowthFacts_SL.pdf

[inactive]: ../inactive_link.html