{{../markdown_header.txt}}

# Econ520 - Advanced Macroeconomic Theory #

## Spring 2016 - Prof. Lutz Hendricks - Term Paper

The term paper picks a topic, critically reviews the literature, and clearly lays out arguments on both sides of the debate.

The paper is due by the last class meeting.

Before the midterm, each student should submit a 1-2 page proposal that:

* states the topic
* outlines the main arguments
* provides at least 5 relevant references

### Expectations

The paper should 

* demonstrate understanding of the literature. Relevant literature might include Fed or IMF publications, the Economist or Wall Street Journal.
* lay out arguments on both sides of a debate.

I do not expect

* innovation, modeling, theory, or original data work.
* that you read academic journal articles. 

There is no prescribed length. Obviously, you don't want to hand in 2 pages.

### Possible topics (but you may choose your own)

Growth:

* Do we need patent protection for innovation to occur?

Fiscal policy:

* Effects of austerity policies in Greece or other European countries.

Monetary policy:

* Should the Fed target asset prices?

Inequality:

* Effects of taxing the rich.
* Causes of rising income inequality. Potential policy responses.

Open economy:

* Are exchange rate devaluations expansionary?
