{{../markdown_header.txt}}

# Econ520 - Advanced Macroeconomic Theory #

## Spring 2017 - Prof. Lutz Hendricks - Term Paper

The term paper picks a topic, critically reviews the literature, and clearly lays out arguments on both sides of the debate.

The paper is due by the last class meeting.

Before the midterm, each student should submit a 1-2 page proposal that:

* states the topic
* outlines the main arguments
* provides at least 5 relevant references

As you write / develop your argument, you should get in touch with me periodically to make sure everything is on track (and to clarify questions).

Please provide all files in **pdf** format (not MS Word). I do not need hardcopies.

### Expectations

The paper should 

* demonstrate understanding of the literature. Relevant literature might include Fed or IMF publications, the Economist or Wall Street Journal.
* lay out arguments on both sides of a debate.

I do not expect

* innovation, modeling, theory, or original data work.
* that you read academic journal articles. 
* that you reach a conclusion. If the experts disagree, I don't expect you to figure it out.

There is no prescribed length. Obviously, you don't want to hand in 2 pages.

Examples of well-written term papers: [Negative interest rates](term_paper/negative_interest_rates_paper.pdf), [Racial inequality](term_paper/racial_inequality_paper.pdf).


### Notes on Writing ###

**Cite your sources.** 
When you make a claim, back it up.

**Nice words come last.** 
First decide what you want to write. Outline that. When you are happy with the substance, fill in the words.

**Visual structure.** 
There should be (sub-)headings that let the reader see at a glance how the document is structured.

### Possible Topics (but You May Choose Your Own) ###

The topic needs to be fairly narrow. Examples:

* You could study the importance of international trade for rising income inequality. Studying all possible causes of rising income inequality would be too broad.
* You could study the pros and cons of a particular tax proposal (e.g., the flat tax).

Below I list potential topics. They are generally phrased more broadly than what you would choose for a term paper.

Growth:

* Do we need patent protection for innovation to occur?
* Why has manufacturing declined in the U.S. (international trade, technical change, ...)?

Business cycles:

* Why was wage growth so slow during the recovery after the Great Recession?

Fiscal policy:

* Effects of austerity policies in Greece or other European countries.

Monetary policy:

* Should the Fed target asset prices?

Inequality:

* Effects of taxing the rich.
* Causes of rising income inequality. Potential policy responses.
* Labor market polarization: what will happen when more and more jobs get mechanized?

Open economy:

* Are exchange rate devaluations expansionary?

# Finding source material

Academic journal articles are generally hard to read. Feel free to look, though, and you will get an idea what professional economists actually do.

Sources with overview articles:

* The Journal of Economic Perspectives 
* Brookings Institution
* Federal Reserve Banks publish articles aimed at explaining research to the general public. Examples are the Economic Letters of the San Francisco Fed.

I would generally avoid political sources (Heritage Foundation; Congress; Cato Institute).

---------