{{../markdown_header.txt}}

# Topics in the Current Policy Debate

## Taxes

[Border Adjustments, Tariffs, VAT, and the Corporate Income Tax](http://conversableeconomist.blogspot.com/2017/01/border-adjustments-tariffs-vat-and.html), Jan 2017

* discusses the implications of corporate tax reforms, including the Trump proposal


---------------