{{../markdown_header.txt}}


## Field Papers in Macro/International ##

A field paper should contain at least a critical literature review. Critical means: the review should identify potential avenues for future research.

In many cases, students will have identified a potential topic by the time they start their field paper. Then it makes sense to keep the literature review short and focus on the initial steps of the proposed research.

Each student should get his/her topic approved by a faculty member at the start.

While field papers are eventually read by 2 faculty members, the "field paper advisor" will have an important say in the outcome.

For 2016, the due date is September 9.

---------