{{../markdown_header.txt}}

## For PhD students

* [Matlab and Programming](http://matlab-introduction.readthedocs.org/en/latest/index.html)
* [Notes on data sources](http://data-sources.readthedocs.org/en/latest/index.html)
* [Tips for finding a topic](../Research/DissertationTips.htm)
* [Tips for first year PhD Students](../Research/PhdTips.htm)
* [Tips for writing](writing_tips.html)
* [Tips for presenting a paper](presentation_tips.html)
* [Tips for using IPUMS data](../Research/ipums_tips.html)
* [Using killdevil at UNC][../Research/killdevil.html]

--------