{{../markdown_header.txt}}

# How can undergraduates get involved in research?

For the most part, students approach faculty members directly and inquire whether he/she can work on one of the faculty member's projects. This works best if the faculty member already knows the student.

For help with this process, please contact the undergraduate research liasion; currently this is myself (Lutz Hendricks).

## Summer research fellowships

* [Mayo Summer Research Fellowship for macro](https://econ.unc.edu/the-hubert-brown-mayo-award-for-summer-research/) 
* Guest Summer Research Fellowship for micro.  

These are announced in late fall, with applications due in March.  

An additional option is the University work-study program.


-----------