{{econ720_header.txt}}

# Econ720: Advanced Macroeconomic Theory (PhD)

### [%ClassTerm]. Prof. Lutz Hendricks. UNC ###

-----------------

[OLG Models][], [Infinite horizon, discrete time][IH1], [Infinite horizon, continuous time][IH2], [Growth][], [Stochastic growth], [Search and Matching][Search], [Contracts][]

## Announcements ##

* Final exam: TBA
* [Syllabus](syllabus720.html)


{{schedule720.mmd}}


-----------------


[inactive]: ../inactive_link.html


