{{econ720_header.txt}}

# Econ720: Advanced Macroeconomic Theory (PhD)

### [%ClassTerm]. Prof. Lutz Hendricks. UNC ###

-----------------

[OLG Models][], [Infinite horizon, discrete time][IH1], [Infinite horizon, continuous time][IH2], [Growth][], [Stochastic growth], [Heterogeneous Agents][], [Search and Matching][Search]

## Announcements ##

* Final exam: Dec-13, 8am, GA 307
* [Syllabus](syllabus720.html)


{{schedule720.mmd}}


-----------------


[inactive]: ../inactive_link.html


