{{econ720_header.txt}}

# Econ720: Advanced Macroeconomic Theory (PhD)

### [%ClassTerm]. Prof. Lutz Hendricks. UNC ###

-----------------

[OLG Models][], [Infinite horizon, discrete time][IH1], [Infinite horizon, continuous time][IH2], [Growth][], [Stochastic growth], [Heterogeneous Agents][], [Search and Matching][Search]

## Announcements ##

* Midterm answers are posted [here](exams/midterm2017_720.pdf).
* Final exam: **Tuesday, Dec-12, 8am**, Gardner 7 (to be confirmed!). Note that this date has changed (switched with Econ770).
* [Syllabus](syllabus720.html)


{{schedule720.mmd}}


-----------------


[inactive]: ../inactive_link.html


