  
## Special dates ## 
  
* Sep-05 (Mon): Labor day 
* Oct-17 (Mon): Midterm: Material covered: TBA 
* Nov-23 (Wed): Thanksgiving 
  
  
## Modern Macro ## 
  
* Aug-24 (Wed): [Modern macro](GenEquil_SL.pdf), Here we talk about methods: how to set up a general equilibrium model and characterize its equilibrium. 
  
  
## Overlapping Generations [OLG Models] ## 
  
* Aug-29 (Mon): [Model](olg/OLG_SL.pdf) 
* Aug-31 (Wed): [Dynamics and steady state](olg/olg_analysis_sl.pdf), [solution for example][inactive], [PS1](olg/OLG_PS.pdf), [answers](olg/OLG_PSA.pdf) 
* Sep-07 (Wed): [Efficiency and Social Security](olg/OLG_SS_SL.pdf), [RQ](olg/OLG_RQ.pdf) (review questions, not to be handed in) 
    * [Bequests](olg/OLG_Bequest_SL.pdf) 
* Sep-12 (Mon): [Money in OLG models](olg/OLG_Money_SL.pdf), [PS2](olg/OLG_Money_PS.pdf), [answers](olg/OLG_Money_PSA.pdf) 
  
  
## Infinite Horizon, Discrete Time Models [IH1] ## 
  
* Sep-14 (Wed): [The growth model](ih1/IH1_SL.pdf) 
* Sep-19 (Mon): [Dynamic programming](ih1/ih1_dp_sl.pdf) 
    * [Competitive equilibrium](ih1/ih1_equil_sl.pdf), [RQ](ih1/IH1_RQ.pdf), [PS3](ih1/IH1_PS.pdf), due Sep-30 
* Sep-21 (Wed): [Dynamic programming theorems](ih1/DP_SL.pdf), [Notes on Dynamic Programming](ih1/Dp_ln.pdf) 
    * [Example: Asset pricing](ih1/IH1_Asset_SL.pdf), [RQ](ih1/ih1_asset_rq.pdf) 
* Sep-26 (Mon): [Cash in advance models](ih1/CIA_SL.pdf), [RQ](ih1/CIA_RQ.pdf), [PS4](ih1/CIA_PS.pdf), due Oct-5 
* Sep-28 (Wed): [Two sector models](ih1/TwoSec_SL.pdf), [RQ](ih1/TwoSec_RQ.pdf) 
    * [Final example](ih1/ih1_final_example_sl.pdf) 
  
  
## Infinite Horizon, Continuous Time Models [IH2] ## 
  
* Oct-03 (Mon): [Solow model](ih2/solow_SL.pdf) 
    * [Optimal control](ih2/OptControl_SL.pdf) 
* Oct-05 (Wed): [The growth model](ih2/Ramsey_SL.pdf) 
* Oct-10 (Mon): [Dynamics and phase diagrams](ih2/PhaseDiagrams_SL.pdf), [RQ](ih2/IH2_RQ.pdf), [PS5](ih2/IH2_PS.pdf), due Oct-19 
* Oct-12 (Wed): [Money in the utility function](ih2/miu_sl.pdf) 
* Oct-19 (Wed): [Perpetual youth](ih2/PerpetualYouth_SL.pdf) 
* Oct-24 (Mon): [Aggregation issues](ih2/Aggregation_SL.pdf) 
  
  
## Endogenous Growth [Growth] ## 
  
* Oct-26 (Wed): [Endogenous growth: AK model](growth/AK_SL.pdf), [RQ](growth/AK_RQ.pdf), [Phase diagram](growth/phase_diagram_sl.pdf) 
* Oct-31 (Mon): [R&D driven growth](growth/RandD_SL.pdf) 
* Nov-02 (Wed): [Increasing varieties](growth/Varieties_SL.pdf), [RQ](growth/RandD_RQ.pdf) 
* Nov-07 (Mon): [Knowledge spillovers and scale effects](growth/ScaleEffects_SL.pdf), [PS6](growth/RandD_PS.pdf), due Nov-21 
* Nov-09 (Wed): [Quality ladders](growth/Schumpeter_SL.pdf) 
  
  
## Stochastic Growth ## 
  
* Nov-14 (Mon): [Stochastic optimization](stochastic/Stochastic_SL.pdf), [Dynamic programming](stochastic/theorems_sl.pdf) -- we will not talk about this in class. Think of it as a simple user guide to the results that are out there. 
    * [Asset pricing](stochastic/AssetTheory_SL.pdf) 
* Nov-16 (Wed): [Extensions](stochastic/asset_extensions_sl.pdf), [RQ](stochastic/Asset_RQ.pdf), [PS7](stochastic/Asset_PS.pdf), due Dec-5 
* Nov-21 (Mon): [Stochastic growth model](stochastic/Stoch_Growth_SL.pdf), [RQ](stochastic/Stoch_Growth_RQ.pdf) 
* Nov-28 (Mon): [Bewley model](stochastic/Bewley_SL.pdf) 
* Nov-30 (Wed): Incomplete markets: , [Huggett 1996](stochastic/huggett96_sl.pdf), [Krusell and Smith](stochastic/Krusell_Smith_SL.pdf) 
  
  
## Search and Matching [Search] ## 
  
* Dec-05 (Mon): [McCall model](search/McCall_SL.pdf) 
* Dec-07 (Wed): [Mortenson-Pissarides](search/MortensonPissarides_SL.pdf), [RQ](search/Search_RQ.pdf) 
  
  
## Contracts ## 
  
* Dec-07 (Wed): [Limited commitment](contracts/Contract1_SL.pdf), [Asymmetric information](contracts/Contract2_SL.pdf), [RQ](contracts/Contracts_RQ.pdf) 
* Dec-07 (Wed): Last class -- examples and Q&A 
  
