  
## Special dates ## 
  
* Sep-21 (Thu): No class (will schedule makeup class) 
* Oct-10 (Tue): Midterm: Material covered: TBA 
* Oct-19 (Thu): Fall break 
* Nov-23 (Thu): Thanksgiving 
  
  
## Modern Macro ## 
  
* Aug-22 (Tue): [Modern macro](GenEquil_SL.pdf), Here we talk about methods: how to set up a general equilibrium model and characterize its equilibrium. 
  
  
## Overlapping Generations [OLG Models] ## 
  
* Aug-24 (Thu): [Model](olg/OLG_SL.pdf) 
* Aug-29 (Tue): [Dynamics and steady state](olg/olg_analysis_sl.pdf), [solution for example](OLG_example.pdf), [PS1](olg/OLG_PS.pdf), [answers](olg/OLG_PSA.pdf) 
* Aug-31 (Thu): [Efficiency and Social Security](olg/OLG_SS_SL.pdf), [RQ](olg/OLG_RQ.pdf) (review questions, not to be handed in) 
    * [Bequests](olg/OLG_Bequest_SL.pdf) 
* Sep-05 (Tue): [Money in OLG models](olg/OLG_Money_SL.pdf), [PS2](olg/OLG_Money_PS.pdf), [answers](olg/OLG_Money_PSA.pdf) 
  
  
## Infinite Horizon, Discrete Time Models [IH1] ## 
  
* Sep-07 (Thu): [The growth model](ih1/IH1_SL.pdf) 
* Sep-12 (Tue): [Dynamic programming](ih1/ih1_dp_sl.pdf) 
* Sep-14 (Thu): [Competitive equilibrium](ih1/ih1_equil_sl.pdf), [RQ](ih1/IH1_RQ.pdf), [PS3](ih1/IH1_PS.pdf), due Sep-19 
* Sep-19 (Tue): [Dynamic programming theorems](ih1/DP_SL.pdf), [Notes on Dynamic Programming](ih1/Dp_ln.pdf) 
    * [Example: Asset pricing](ih1/IH1_Asset_SL.pdf), [RQ](ih1/ih1_asset_rq.pdf) 
* Sep-26 (Tue): [Cash in advance models](ih1/CIA_SL.pdf), [RQ](ih1/CIA_RQ.pdf), [PS4](ih1/CIA_PS.pdf), due Sep-26 
* Sep-28 (Thu): [Two sector models](ih1/TwoSec_SL.pdf), [RQ](ih1/TwoSec_RQ.pdf) 
    * [Final example](ih1/ih1_final_example_sl.pdf) 
  
  
## Infinite Horizon, Continuous Time Models [IH2] ## 
  
* Oct-03 (Tue): [Solow model](ih2/solow_SL.pdf) 
    * [Optimal control](ih2/OptControl_SL.pdf) 
* Oct-05 (Thu): [The growth model](ih2/Ramsey_SL.pdf) 
    * [Dynamics and phase diagrams](ih2/PhaseDiagrams_SL.pdf), [RQ](ih2/IH2_RQ.pdf), [PS5](ih2/IH2_PS.pdf), due TBA 
* Oct-12 (Thu): [Money in the utility function](ih2/miu_sl.pdf) 
* Oct-17 (Tue): [Perpetual youth](ih2/PerpetualYouth_SL.pdf) 
* Oct-24 (Tue): [Aggregation issues](ih2/Aggregation_SL.pdf) 
  
  
## Endogenous Growth [Growth] ## 
  
* Oct-26 (Thu): [Endogenous growth: AK model](growth/AK_SL.pdf), [RQ](growth/AK_RQ.pdf), [Phase diagram](growth/phase_diagram_sl.pdf) 
* Oct-31 (Tue): [R&D driven growth](growth/RandD_SL.pdf) 
* Nov-02 (Thu): [Increasing varieties](growth/Varieties_SL.pdf), [RQ](growth/RandD_RQ.pdf) 
* Nov-07 (Tue): [Knowledge spillovers and scale effects](growth/ScaleEffects_SL.pdf), [PS6](growth/RandD_PS.pdf), due TBA 
    * [Quality ladders](growth/Schumpeter_SL.pdf) 
* Nov-09 (Thu): [Quality ladders with firm dynamics](growth/Schumpeter2_SL.pdf) 
  
  
## Stochastic Growth ## 
  
* Nov-14 (Tue): [Stochastic optimization](stochastic/Stochastic_SL.pdf) 
    * [Dynamic programming](stochastic/theorems_sl.pdf) -- we will not talk about this in class. Think of it as a simple user guide to the results that are out there. 
    * [Asset pricing](stochastic/AssetTheory_SL.pdf) 
* Nov-16 (Thu): [Extensions](stochastic/asset_extensions_sl.pdf), [RQ](stochastic/Asset_RQ.pdf), [PS7](stochastic/Asset_PS.pdf), due TBA 
* Nov-21 (Tue): [Stochastic growth model](stochastic/Stoch_Growth_SL.pdf), [RQ](stochastic/Stoch_Growth_RQ.pdf) 
  
  
## Heterogeneous Agents ## 
  
* Nov-28 (Tue): [Bewley model](hetero/Bewley_SL.pdf) 
    * Wealth distribution: , [Motivation and baseline model](hetero/huggett1996_sl.pdf) 
* Nov-30 (Thu): [Stochastic aging](hetero/castaneda_sl.pdf), [Self-employment](hetero/wealth_selfempl_sl.pdf) 
* Dec-05 (Tue): Aggregate uncertainty: , [Krusell and Smith](hetero/Krusell_Smith_SL.pdf) 
  
  
## Search and Matching [Search] ## 
  
* Dec-05 (Tue): [McCall model](search/McCall_SL.pdf) 
* Dec-05 (Tue): [Mortenson-Pissarides](search/MortensonPissarides_SL.pdf), [RQ](search/Search_RQ.pdf) 
  
