{{econ720_header.txt}}


# Econ720: Advanced Macroeconomic Theory (PhD)

### [%ClassTerm]. Prof. Lutz Hendricks. UNC

-----------------

## Course objective:

Econ720 is the first course in the macro PhD sequence. Its objective is to teach basic versions of the standard models commonly used in macroeconomics. In parallel, the course develops the mathematical methods used to characterize the equilibria of the models. This is a pure theory course.

## Organization:

* Two lectures per week: MW, 1:00-2:15, GA 307
* Recitation: Fri 1:25-2:15, GA 307
* TA: Yanran Guo

## Grading:

* Midterm: 40%. Final: 50%. Problem sets: 10%. Exams are closed book and cover all material taught.
* Review problems are for your practice and not to be turned in. Many are questions from previous exams.
* If a student misses a midterm, the weight of that midterm in the course grade will be added to the weight on the student’s final.  An exception will be made for [University-approved absences](http://catalog.unc.edu/policies-procedures/attendance-grading-examination/). Students with this type of absence may request a make-up examination at a time convenient to both student and instructor.

## Text:

* Acemoglu, Introduction to Modern Economic Growth, MIT Press, ISBN-13: 978-0691132921
* Additional readings are in the slides.

## Rules:

* Questions and comments are always welcome.
* You should download the slides before each class. However, I tend to change details even after posting the slides.

## Previous Exams ##

* Qualifying exams: [August 2009][], [January 2010][], [August 2010][], [January 2011][], [August 2011][], [January 2012][], [August 2012][],
[January 2013][], [August 2013][], [January 2014][], [August 2014][], [January 2015][], [August 2015](exams/Quals_2015_Aug.pdf), [January 2016][], [August 2016][], [January 2017][], [August 2017](exams/Quals_2017_Aug.pdf), [May 2018](exams/Quals_2018_May.pdf).  
* Final exams: [2009][fin2009], [2010][fin2010], [2011][fin2011], [2012][fin2012], [2013][fin2013], [2014][fin2014], [2015](exams/final2015_720.pdf), [2016](exams/final2016_720.pdf), [2017](exams/final2017_720.pdf). 
* Midterms: [2008][mid2008] (Iowa State), [2009][mid2009], [2009 take 3][mid2009 take 3], [2010][mid2010], [2011][mid2011], [2012][mid2012], [2013][mid2013], [2014][mid2014], [2015](exams/midterm2015_720.pdf), [2016](exams/midterm2016_720.pdf), [2017](exams/midterm2017_720.pdf).  
* If answers are missing, the exam questions are usually reused as problem sets. 

## Additional Notes ##

* Reading material is listed at the end of the slides.
* Dirk Krueger’s [Macroeconomic Theory][] manuscript ([2012 version][]; this tends to move around on the web).
* Per Krusell’s [Real Macroeconomic Theory][] manuscript  


-----------

[Macroeconomic Theory]: http://www.ssc.wisc.edu/~aseshadr/econ714/MacroTheory.pdf
[Real Macroeconomic Theory]: http://www.econ.umn.edu/%7Evr0j/8108-14/newmanu.pdf


  [August 2009]: exams/Quals_2009_Aug.pdf
  [January 2010]: exams/Quals_2010_Jan.pdf
  [August 2010]: exams/Quals_2010_Aug.pdf
  [January 2011]: exams/Quals_2011_Jan.pdf
  [August 2011]: exams/Quals_2011_Aug.pdf
  [January 2012]: exams/Quals_2012_Jan.pdf
  [August 2012]: exams/Quals_2012_Aug.pdf
  [January 2013]: exams/Quals_2013_Jan.pdf
  [August 2013]: exams/Quals_2013_Aug.pdf
  [January 2014]: exams/Quals_2014_Jan.pdf
  [August 2014]: exams/Quals_2014_Aug.pdf
  [January 2015]: exams/Quals_2015_Jan.pdf
  [January 2016]: exams/Quals_2016_Jan.pdf
  [August 2016]: exams/Quals_2016_Aug.pdf
[January 2017]: exams/Quals_2017_Jan.pdf
  [fin2009]: exams/final2009_720.pdf
  [fin2010]: exams/final2010_720.pdf
  [fin2011]: exams/final2011_720.pdf
  [fin2012]: exams/final2012_720.pdf
  [fin2013]: exams/final2013_720.pdf
  [fin2014]: exams/final2014_720.pdf
  [mid2008]: exams/Midterm2008_602.pdf
  [mid2009]: exams/Midterm2009_720.pdf
  [mid2009 take 3]: exams/Midterm3_2009_720.pdf
  [mid2010]: exams/midterm2010_720.pdf
  [mid2011]: exams/midterm2011_720.pdf
  [mid2012]: exams/midterm2012_720.pdf
  [mid2013]: exams/midterm2013_720.pdf
  [mid2014]: exams/midterm2014_720.pdf


