{{econ920_header.txt}}
{{../markdown_header.txt}}


# Econ920: Dissertation Workshop

### [%ClassTerm]. Prof. Lutz Hendricks. UNC

-----------------


#Announcements #

* Class meets Monday 1:30 in Hamilton 150 (though we will try Gardner while it's not too noisy)
* We plan to meet once a week.
* Check this web site (www.lhendricks.org) regularly for updates.


# Organization #

### Presentation Schedule Spring 2017 ###

Date  | Speaker  | Topic  |  
---- | ---- | ----- |  
11-Jan  | Organizational meeting | |  
16-Jan  | Andrew G | [Regressive Welfare Effects of Housing Bubbles](papers2017/graczyk_jan.pdf) |  
23-Jan  | Alex P | [Border Crossings and Trade](papers2017/pearson_jan.pdf) |  
30-Jan  | Karlye | TBA |  
06-Feb  | | |  
13-Feb  | | |  
20-Feb  | Kanat | TBA |  
27-Feb  | Jennifer | TBA |  
06-Mar  | Gonzalo | TBA |  
13-Mar  | Spring break | |  
20-Mar  | Wenting | TBA |  
27-Mar  | David L | TBA |  
03-Apr  | Calebe | TBA |  
10-Apr  | | |  
17-Apr  | | |  
24-Apr  |  |  |



### Presentation Schedule Fall 2016 ###

Date  | Speaker  | Topic  |  
----  | ------  | -------  |  
Aug-24  | n/a  | Introductory meeting  |  
Sep-8  | Andrew G  | [The Source of Aggregate Inequality: Employment and Income Changes from 1999 to 2014](papers2016/graczyk_sep.pdf)  |  
Sep-15  | Alex  | [Resource Demand Changes and Spatial Development: Evidence from Above](papers2016/pearson_sep.pdf)  |  
Sep-22  | Ken  | TBA  |  
Sep-29  | Jennifer  | [Return to Capital: Evidence from firm level data of non-financial firms](papers2016/rhee_sep.pdf) |  
Oct-6  | Wenting  | [Mergers and Acquisitions, Technological Change and Inequality](papers2016/ma_oct.pdf)  |  
Oct-13  | Gonazalo  | [Corporate Default Risk in Emerging Markets](papers2016/asis_oct.pdf)  |  
Oct-20  | Fall break  | n/a  |  
Oct-27  | Karlye  | [Tamper Tantrums](papers2016/dilts_oct.pdf)  |  
Nov-3  | Andrew H | [Secular stagnation and bubble boom-bust](papers2016/hanson_nov.pdf) |  
Nov-10  | Kanat | [The Allocation of Talent in Brazil and India](papers2016/abdullah_nov.pdf) |  
Nov-17  | David  | [Monetary Policy Regimes and Real Estate Prices](papers2016/leather_nov.pdf)  |  
Nov-24  | n/a  | Thanksgiving  |  
Dec-1   | Calebe   | [Global Uncertainty and International Business Cycles](papers2016/figueiredo_nov.pdf)  |


### Objective ###

Provide students at the dissertation stage with regular feedback on their research.

### Introductory Meeting ###

Students briefly introduce their research and describe their progress.

Sign up for presentation slots.

### Student Presentations ###

Presenters: please send me your papers **at least 1 week** before the presentation. 

I want to see your slides a few days before the presentation - to make sure they fit the time frame etc.
pdf files only, please.

You may find helpful: 

* [Presentation tips](../teaching/presentation_tips.html)
* [Tips for finding a topic](../Research/DissertationTips.htm)

----------
