{{econ920_header.txt}}
{{../markdown_header.txt}}


# Econ920: Dissertation Workshop

### [%ClassTerm]. Prof. Lutz Hendricks. UNC

-----------------


#Announcements #

* Class is scheduled for MWF, 12:30-1:45, Hanes 107.
* We plan to meet once a week.
* First class meeting: Aug-24
* I will try to get us a room in Gardner (at a more convenient time)
* Check this web site (www.lhendricks.org) regularly for updates.


# Organization #

### Presentation Schedule ###

Date	| Speaker	| Topic	|  
----	| ------	| -------	|  
Aug-24	| n/a	| Introductory meeting	|  
Aug-31 | ||
Sep-7 |  ||
Sep-14 | | |
Sep-21 | | |
Sep-28 | | |
Oct-5 | | |
Oct-12 | | |
Oct-19 | | |
Oct-26 | | |
Nov-2 | | |
Nov-9 | | |
Nov-16 | | |
Nov-23 | Thanksgiving ||
Nov-30 | | |

### Objective ###

Provide students at the dissertation stage with regular feedback on their research.

### Introductory Meeting ###

Students briefly introduce their research and describe their progress.

Sign up for presentation slots.

### Student Presentations ###

Presenters: please send me your papers **at least 1 week** before the presentation. 

I want to see your slides a few days before the presentation - to make sure they fit the time frame etc.
pdf files only, please.

You may find helpful: 

* [Presentation tips](../teaching/presentation_tips.html)
* [Tips for finding a topic](../Research/DissertationTips.htm)

----------
