{{econ920_header.txt}}
{{../markdown_header.txt}}


# Econ920: Dissertation Workshop

### [%ClassTerm]. Prof. Lutz Hendricks. UNC

-----------------


#Announcements #

* New class time: Thr 2-3:15pm, Gardner 7.
* We plan to meet once a week.
* Check this web site (www.lhendricks.org) regularly for updates.


# Organization #

### Presentation Schedule ###

Date	| Speaker	| Topic	|  
----	| ------	| -------	|  
Aug-24	| n/a	| Introductory meeting	|  
Sep-8	| Andrew G	| [The Source of Aggregate Inequality: Employment and Income Changes from 1999 to 2014](papers2016/graczyk_sep.pdf)	|  
Sep-15	| Alex	| [Resource Demand Changes and Spatial Development: Evidence from Above](papers2016/pearson_sep.pdf)	|  
Sep-22	| Ken	| TBA	|  
Sep-29	| Jennifer	| TBA	|  
Oct-6	| Wenting	| TBA	|  
Oct-13	| Calebe	| TBA	|  
Oct-20	| Gonazalo	| TBA	|  
Oct-27	| Karlye	| TBA	|  
Nov-3	| Andrew H | TBA |  
Nov-19	| Kanat | TBA |  
Nov-24	| n/a	| Thanksgiving	|  
Nov-17	| David	| TBA	|  

### Objective ###

Provide students at the dissertation stage with regular feedback on their research.

### Introductory Meeting ###

Students briefly introduce their research and describe their progress.

Sign up for presentation slots.

### Student Presentations ###

Presenters: please send me your papers **at least 1 week** before the presentation. 

I want to see your slides a few days before the presentation - to make sure they fit the time frame etc.
pdf files only, please.

You may find helpful: 

* [Presentation tips](../teaching/presentation_tips.html)
* [Tips for finding a topic](../Research/DissertationTips.htm)

----------
