{{../markdown_header.txt}}

# Application Form: Economics Honors Program 2018/19

Submit to Lutz Hendricks (lhendri at email dot unc dot edu) by May 7, 2018.

## Information about you

Name:

Email: 

Major(s):

Expected term and year of graduation:

Cumulative GPA at UNC:

Cumulative GPA in economics courses at UNC:

Why do you want to write an honors thesis?

<br><br>

Anything else I should know?

<br><br>

## Economics courses that you have taken

|------|------|------|-------|
| Title | Year | Instructor | Grade |
| Econ400: Statistics | | | |
| Econ410: Intermediate micro | | | |
| Econ420: Intermediate macro | | | |
| Econ570: Econometrics | | | |
| Other 400 or 500 level economics courses | | | |
| 1.    | | | |
| 2.  | | | |
| 3.  | | | |
| 4.  | | | |
| 5.  | | | |

## Describe your area of interest

If you have a specific topic in mind, please describe it below. If not, tell me about areas that you may want to research and why they interest you.

<br><br><br><br>


-------------------