{{../markdown_header.txt}}

# Communicating About Your Thesis #

I have set up a `slack` for Econ691H. If you need an invite, please contact me.

`Slack` is an alternative to email. The main benefit is that conversations stay organized by thread or topic.

It probably makes sense to invite your advisor to join `slack` so he/she can follow the conversation.

I propose the following **organization**:

1. Generate several channels for each thesis, such as `Hendricks-data` or `Hendricks-model`.

	There you can post questions about your own thesis or you can comment on the theses of others.
	You can also post status updates ("I found a data source") and documents.
	Remember that these comments are visible to all.
	For communication that should not be visible to all, use email.

2. If you want to discuss topics of more general interest, create a new channel.

	Examples: How to implement specific econometric procedures in `Stata`? Does anyone know how to find data on `X`?

The use of `slack` is somewhat experimental. If you know of a better tool, please let me know.

-----------