{{../markdown_header.txt}}

# Econ692H - Spring 2018 #

[Syllabus](syllabus692h.html)


## Announcements

* Jan-16: An opportunity for a *pre*-doctoral [fellowship at Berkeley](material/predoc.pdf). If you plan to attend grad school in economics, this could be a great opportunity.
* Dec-14: A general note on the feedback that I provide: *advisors rule*. When in doubt, follow your advisors comments, not mine. Just let me know when that happens.

--------------