{{../markdown_header.txt}}

# Econ691H - Fall 2017 #

[Syllabus](syllabus691h.html) | [Basic information and application process](intro.html) | [FAQ](honors_faq.html)

[Useful links](links.html) | [Presentation tips](../teaching/presentation_tips.html) | [Writing tips](../teaching/writing_tips.html)  |  [Developing empirical models](empirical_models.html)  |  [Theoretical models](theory_models.html) 

Acknowledgement: I am drawing heavily on Klara Peter's material from past years.

## Announcements

* Oct-30: Please sign up for final **presentation** dates (between Nov-14 and end of classes) and for **discussions**. Email me with the data you want and with the thesis you want to present. 
	* If you do not sign up by Nov-7, I will assign a presentation date and a thesis to discuss!
	* The current schedule for presentations is [here](final_presentations.html).

{{schedule691h.mmd}}

--------------