{{../markdown_header.txt}}

# Econ691H - Fall 2018 #

[Syllabus](syllabus691h.html) | [Basic information and application process](intro.html) | [FAQ](honors_faq.html)

[Useful links](links.html) | [Presentation tips](../teaching/presentation_tips.html) | [Writing tips](../teaching/writing_tips.html)  |  [Developing empirical models](instructions/empirical_models.html)  |  [Theoretical models](instructions/theory_models.html) 

A general note on the feedback that I provide on your theses: *advisors rule*. When in doubt, follow your advisors comments, not mine. Just let me know when that happens.

## Announcements

* Jul-5: [Notes on how to prepare during the summer](instructions/summer_prep.html)

## Schedule

We meet as a class only a few times at the start of the semester. Afterwards, we will meet one-on-one.
  
* Aug-22 (Wed): [Syllabus](syllabus691h.html)
	* [Finding a topic](instructions/finding_topic.html),  [Finding an advisor](instructions/finding_advisor.html)
	* [Useful links](links.html)
* Aug-27 (Mon): 
	* [Finding a topic: examples](instructions/finding_topic_examples.html)
	* [Writing a literature review](instructions/lit_review.html),  [Reading papers](instructions/how_to_read.html)
	* [Working with data](instructions/work_with_data.html)
* Sep-24 (Mon):
	* Progress report due
* Oct-22 (Mon):
	* Preliminary proposal due
* Nov-19 (Mon):
	* Final proposal due

Acknowledgement: I am drawing heavily on Klara Peter's material from past years.

--------------