{{../markdown_header.txt}}

# Econ692H - Spring 2018 #

[Syllabus](syllabus692h.html)


## Announcements

* Feb-1: An [RA position at Wharton](material/PWBM RA Position Description.pdf)
* Jan-25: Another opportunity to publish your work: The [Dartmouth Undergraduate Journal of Politics, Economics and World Affairs](https://www.dartmouthujpew.com).
* Jan-24: You can submit your paper for publication and to earn the "best undergraduate paper award" from the [IAES](http://www.iaes.org/best-undergraduate-paper-award/)
* Jan-16: An opportunity for a *pre*-doctoral [fellowship at Berkeley](material/predoc.pdf). If you plan to attend grad school in economics, this could be a great opportunity.
* Dec-14: A general note on the feedback that I provide: *advisors rule*. When in doubt, follow your advisors comments, not mine. Just let me know when that happens.

--------------