{{../markdown_header.txt}}

## Final draft presentations and dicussants

| Name	| Date	| Thesis	| Discussant	|  
| ---	| ---	| -----	| -----	|  
| Burriss	| 	| The Effect of Social Ties on Mental Health of High School Students in the United States	| Jimmy Chin	|  
| Cecotti	| 	| Impact of constitutional reform on domestic workers in Brazil	| Bill Wang	|  
| Chin	| Nov-28	| Intergenerational Earnings Mobility in China	| 	|  
| Dolder	| Nov-30	| Risk Preferences and Crime	| 	|  
| Li	| 	| Proposing before Match: A New Way to Look at Marriage Matching	| Katie Rha	|  
| Mccallen	| 	| Geopolitical risk and asset prices	| 	|  
| Qiao	| 	| Diffusion of Medical Treatment and Market Competitiveness	| 	|  
| Rha	| Nov-21	| Central bank communication	| 	|  
| Roberts	| 	| The Impact of State-Level Abortion Restrictions on Female Labor Supply	| 	|  
| Saunders	| 	| Price level path targeting	| 	|  
| Suttoni	| 	| Effectiveness of CDFI Loans to Sm all Businesses on Job Growth in the United States	| 	|  
| Wang	| 	| Migrant labor in Singapore	| 	|  
| Xia	| 	| The Short-run Welfare Assessment of Two New Energy Vehicle Policies in China	| 	|  
| Ye	| Nov-28	| REIT Cash Flow Variability and Portfolio Diversification by Property Type	| 	|  

--------------