{{../markdown_header.txt}}

# Finding and Advisor #

First, pick a **broad topic**, such as income inequality, monetary policy, health, ...

Then look for faculty members with expertise in this area. UNC Econ faculty is listed [here](http://econ.unc.edu/people/faculty/) with their fields of interest. The following is a rough classification:

* Microeconomic theory (Biglaiser, Norman, Parreiras, Li, Yates, Woodward)* Macroeconomics (Francis, Alder, Parke, Rabinovic)* International economics (Conway, Charina, Alder, Rosefielde)* Financial/Time-series econometrics (Ghysels, Hill, Aguilar, Hansen)* Microeconometrics (Guilkey, Kim, Verdier)* Labor/education economics (Flabbi, Fruehwirth, Peter, Turchi)* Health economics (Gilleskie, Guilkey)* Industrial organization (McManus, Williams)* Crime economics (Tauchen)* Environmental economics (Yates)* Development economics (Peter-micro; Conway and Alder-macro)

Look at potential faculty members' web sites for their working papers and publications. You are looking for someone with an active research agenda.

Schedule appointments with a few potential advisors.

**Prepare**. Think about potential topics and questions of interest. The more specific you can be, the better.

In your meetings, be concise and precise.

----------------