{{../markdown_header.txt}}

# Undergraduate Honors Program: FAQ

1. Can I get honors in two subjects?

	In principle, the answer is "yes." You would have to fulfill all of the requirements for graduating with honors in economics, including the thesis requirement. In most cases, this would be difficult.

2. Do I need to write a thesis?

	Yes. A thesis is required for graduating with honors.

3. How do I find an advisor?

	Early in the fall semester, when you have settled on a broad topic, I will suggest potential advisors to contact.

-------------