{{../markdown_header.txt}}

# Undergraduate Honors Program: FAQ

1. Can I get honors in two subjects?

	In principle, the answer is "yes." You would have to fulfill all of the requirements for graduating with honors in economics, including the thesis requirement. In most cases, this would be difficult.

2. Do I need to write a thesis?

	Yes. A thesis is required for graduating with honors.

3. How do I find an advisor?

	Early in the fall semester, when you have settled on a broad topic, I will suggest potential advisors to contact.

4. Does my thesis need to have an empirical component?

	No. You can write a pure theory thesis. Most theses end up being mostly empirical because empirical methods are easier to learn than the skills required to write a quality theory paper.
	
5. How can I prepare during the summer?
	1. If your topic will likely be empirical, you can brush up on your econometrics and statistical programming skills.
	2. If you are fairly certain about your topic, you can start reading up on it. I can point you to a faculty member who can get you started on literature.

6. What software should I use for empirical analysis?

	Most people use STATA. Personally, I object to the absurd scripting languages implemented in most Stats packages (the exception being `R`). I don't use Stats packages and therefore know little about them. My recommendation would be either `Matlab` or any other programming language that you happen to know well. For most reasonably popular languages, you will find libraries that implement statistical analysis and data handling. 

	My web site contains an [Intro to Matlab][Matlab Intro].

-------------

[Matlab Intro]: http://matlab-introduction.readthedocs.org/en/latest/matlab_intro.html