{{../markdown_header.txt}}

# Undergraduate Honors Program: Introduction
### College Of Arts And Sciences – Department Of Economics

The Department of Economics honors program offers outstanding economics students the opportunity to work closely with an individual faculty member on a specialized research topic of the student’s choice during the senior year.  Completing a successful honors thesis is the only way to graduate with honors or highest honors in economics at UNC.

Students writing an honors thesis are required to take **ECON 691H** in Fall 2017 and **ECON 692H** in Spring 2018.  

During the fall semester, students will find a thesis advisor, develop an economics-related research topic, collect data, and prepare a thesis proposal consisting of the review of literature and theoretical and/or empirical models.  

In their spring semester, students whose research proposals are accepted will take ECON 692H.  During this course, students will complete their thesis, receiving honors or highest honors status after an oral defense in front of a faculty board.  Anyone can browse a list of past Honors theses at the [Honors Thesis Archive](http://www.unc.edu/depts/honors/thesis_view.shtml).  

## Application Process

Students with a 3.5 grade point average in economics courses and 3.5 in all University course work are eligible to apply for this two-course program (ECON 691H and 692H).  However, the selected students generally have a higher grade point average than 3.5.  

In addition to GPA, we also consider previous economics courses students have taken.  It is required to earn high grades in ECON 400 (or a substitute in statistics), ECON410, ECON420, and in at least one 400- or 500-level field course in economics.  

Students should plan on taking ECON 570 Econometrics the first semester of their senior year at the latest. Familiarity with and access to a statistical analysis program such as STATA is also highly recommended. 

If you would like to be considered for the Honors Program in the Department of Economics in your senior year, please fill out the [application form](honors_application.pdf) and submit it to Ms. Cindy Wunder (<wunder@email.unc.edu>) by **Friday, May 8, 2017**.  If you submit your application before Spring 2017 grades are in, you must update it once these grades become available.

Acceptance decisions will be made by June 1, 2017.  

For questions, contact [Lutz Hendricks](http://lhendricks.org).

-------------------------