{{../markdown_header.txt}}

# Undergraduate Honors Program: Introduction
### College Of Arts And Sciences – Department Of Economics

The Department of Economics honors program offers outstanding economics students the opportunity to work closely with an individual faculty member on a specialized research topic of the student’s choice during the senior year.  Completing a successful honors thesis is the only way to graduate with honors or highest honors in economics at UNC.

Students writing an honors thesis are required to take **ECON 691H** in Fall 2017 and **ECON 692H** in Spring 2018.  

Students must be in Chapel Hill during both semesters.

During the fall semester, students will find a thesis advisor, develop an economics-related research topic, collect data, and prepare a thesis proposal consisting of the review of literature and theoretical and/or empirical models.  

In their spring semester, students whose research proposals are accepted will take ECON 692H.  During this course, students will complete their thesis, receiving honors or highest honors status after an oral defense in front of a faculty board.  Anyone can browse a list of past Honors theses at the [Honors Thesis Archive](http://www.unc.edu/depts/honors/thesis_view.shtml).  


## Benefits of Writing an Honors Thesis

1. Graduate with honors or highest honors (indicated on your transcript).
2. Demonstrate skills to potential employers, such as
	3. working independently
	4. working with data
	5. econometric skills
6. Gain experience with actual research, in close collaboration with experienced research faculty.
7. More informative / stronger reference letters for job applications.
8. A foot in the door for graduate school.

Past honors students have indicated that their honors thesis work played an important role during job interviews.

## Application Process 2018

Requirements:

1. GPA or 3.5 in economics courses and overall. Accepted students typically have higher GPAs.
2. High grades in ECON 400 (or a substitute in statistics), ECON410, ECON420, and in at least one 400- or 500-level field course in economics.
3. ECON470 (Econometrics) should be taken before the fall of the senior year. 
	4. During 2018/19 only, Econ570 can be used to meet the Econ470 requirement.
	5. During 2018/19 only, Econ470 or 570 may be taken in the fall of the senior year, but this is not recommended.

Familiarity with statistical software (e.g., STATA) or a programming language (e.g., Matlab) is highly recommended. 

To be considered, please submit the [application form](https://docs.google.com/document/d/19DyBNXA4LVh3a0BPpWSEF_NJdJdnvcDzz_bqMF9BjIQ/edit?usp=sharing) by email it to [Lutz Hendricks][LH] by **Wednesday, May 30, 2018** (lhendri at email dot unc dot edu).  

If you submit your application before Spring 2018 grades are in, you must update it once these grades become available.

I plan to interview all successful applicants in person. This can be done via skype / facetime if you are not in town after your application has been submitted.

Acceptance decisions will be made by June 1, 2018.  

For questions, contact [Lutz Hendricks][LH]. Also see my [FAQ](honors_faq.html)

-------------------------

[LH]: http://lhendricks.org