{{../markdown_header.txt}}

# Econ691H: Useful Links #

## Conference opportunities

[Carroll Round](https://carrollround.georgetown.edu/)

* a conference where undergraduate students present research in international economics
* takes place annually in April

[UNC Celebration of Undergraduate Research](http://our.unc.edu/symposia/cur/)

* UNC undergraduates present their research
* takes place annually in April

[List of conference opportunities for undergraduate research](https://www.aeaweb.org/resources/students/undergrad-research)

UNC provides [funding for travel](http://cifd.unc.edu/?id=271) to present research.

More [UNC funding opportunities](http://honorscarolina.unc.edu/research/senior-honors-thesis/)

## Guides and Tips ##

* [UNC's library](https://guides.lib.unc.edu/econ691h) has a resource page for econ honors theses. Librarians can be great resources for finding data and references.
* [Harvard](https://economics.harvard.edu/pages/senior-thesis) offers a nice guide. Note, in particular, the section on "finding a topic" in the "Logistics" document.
* [Writing tips for economics research papers](http://www.people.fas.harvard.edu/~pnikolov/resources/writingtips.pdf) by P. Nikolov.
* [Honors Carolina](http://honorscarolina.unc.edu/research/senior-honors-thesis/) posts official guidelines for honors theses and other helpful info.

## Past Honors Theses [pastTheses]

At the [Carolina Digital Repository](https://cdr.lib.unc.edu) you can see past honors theses. 

Steps:

* sign in with onyen
* click on `Departments` tab and select `Department of Economics`
* in `Folders` select `UNC Chapel Hill Undergraduate Honors Theses Collection`
* in the box that shows `Default` select `Date deposited (newest)`

------------------