{{../markdown_header.txt}}

# Econ691H: Useful Links #

[Carroll Round](https://carrollround.georgetown.edu/)

* a conference where undergraduate students present research in international economics
* takes place annually in April

[UNC Celebration of Undergraduate Research](http://our.unc.edu/symposia/cur/)

* UNC undergraduates present their research
* takes place annually in April

[List of conference opportunities for undergraduate research](https://www.aeaweb.org/resources/students/undergrad-research)

UNC provides [funding for travel](http://cifd.unc.edu/?id=271) to present research.


------------------