{{../markdown_header.txt}}

# Writing a Literature Review #

Sources:

* [google scholar](scholar.google.com)
* [jstor](jstor.org)
* ask your librarian

Good places to get started:

* [Journal of Economic Perspectives](https://www.aeaweb.org/jep/)
* [Journal of Economic Literature](https://www.aeaweb.org/jel/)
* [Handbook series](https://www.elsevier.com/books/book-series/handbooks-in-economics). Expert written literature reviews.

Tricks:

* Start with a recent article. Read its literature review. Follow its citations.
* Start with an article that is highly relevant. See who cites it.

## Synthesizing ##

A good literature review is **not** a list of paper summaries. It uncovers a structured argument that is made in the literature.

Your goal is to determine areas of agreement and disagreement and their causes.

Ideally, you end up with a **coherent narrative** on how the literature has evolved. If you are lucky, the literature starts simple and then cumulatively builds on previous work. Unfortunately, this rarely works in economics.

**Example**: measuring the human capital stock of a country

1. Early literature: years of schooling. Unanswered question: how much does a year of schooling contribute to output?
2. Mincer literature: Use a [Mincer equation](https://en.wikipedia.org/wiki/Mincer_earnings_function) to convert years of schooling into efficiency units of labor.
3. Implicit assumption: a year of schooling contributes the same to output in all countries. We should account for "school quality" differences.
4. Production function approach: To measure "school quality," assume a human capital production function and measure inputs (such as school spending).
5. Drawback: findings depend on lot on the production function and identification strategy. Identification is very indirect.
6. Immigrant earnings approach: Measure human capital of a country by observing its workers in the U.S. labor market.
7. Drawback: assumptions on migrant selection must be made. Etc ...

## Evaluating Sources ##

Searching [google scholar](scholar.google.com) for references yields thousands of hits. You need to select promising ones. A source is promising if:

* it is published in a good journal
* it is written by a prominent author (e.g., at a top university)
* it is cited many times

Use journal rankings (such as [repec's](https://ideas.repec.org/top/top.journals.simple.html)) to get a sense of the quality of a journal. Rankings often disagree a lot, but they agree on who is near the top.

--------