  
## Regular Class Meetings ## 
  
* Aug-22 (Tue): [Syllabus](syllabus691h.html)
	* [Finding a topic](finding_topic.html),  [Finding an advisor](finding_advisor.html)
	* [Communicating about your thesis](communication.html),  [Useful links](links.html)
* Aug-24 (Thu): 
	* [Finding a topic: examples](finding_topic_examples.html)
	* [Writing a literature review](lit_review.html),  [Reading papers](how_to_read.html)
	* [Working with data](work_with_data.html), [CPS example](cps_earnings.html)
* Aug-29 (Tue): No class. Individual meetings in my office.
* Aug-31 (Thu): No class. Individual meetings in my office.
* Sep-05 (Tue): Presentation by library representative on finding references and data.
	* Bring your laptop.
* Sep-07 (Thu): No class. Individual meetings in my office. 
* Sep-12 (Tue): No class. Individual meetings in my office.
* Sep-14 (Thr): No class. Individual meetings in my office.

## Mid Semester Presentations

* Sep-19 (Tue): Short presentations on student topics
	* Lucas Mccallen, Bill Wang, Zach Saunders
	* You may prepare slides, but are not required to do so.
	* The main purpose is to get feedback on how to sharpen your topic.
* Sep-21 (Thu): No class. Individual meetings in my office. 
* Sep-26 (Tue): Short presentations on student topics
	* Katie Rha, Sarah Suttoni, Jimmy Chin
* Sep-28 (Thu): Short presentations on student topics
	* Zicheng Ye (who else is volunteering?)
* Oct-03 (Tue): Short presentations on student topics
	* Ben Dolder, Andre Cecotti (who else is volunteering??)
* Oct-05 (Thu): No class. Individual meetings in my office. 
* Oct-10 (Tue): Student presentations.
	* Joe Qiao
* Oct-12 (Thu): Student presentations.
	* Lucas Mccallen
* Oct-17 (Tue): Student presentations.
	* Jiaxi Li
* Oct-19 (Thu): Fall break 
* Oct-24 (Tue): TBD 
	* Preliminary drafts are due.
* Oct-26 (Thu): TBD 
* Oct-31 (Tue): TBD 


## Final Draft Presentations ##

* Nov-02 (Thu): No class. Individual meetings in my office. 
* Nov-07 (Tue): No class. Individual meetings in my office.
* Nov-09 (Thu): No class. Individual meetings in my office.
* Nov-14 (Tue): Student presentations. 
	* Final drafts are due Nov-14.
* Nov-16 (Thu): Student presentations.
* Nov-21 (Tue): Student presentations.
	* Katie Rha
* Nov-23 (Thu): Thanksgiving 
* Nov-28 (Tue): Student presentations.
	* Zicheng Ye, Jimmy Chin
	* Discussions of other student's projects are due.
* Nov-30 (Thu): Student presentations. 
	* Ben Dolder
* Dec-05 (Tue): Student presentations. (Last class)

| Name	| Date	| Thesis	| Discussant	|  
| ---	| ---	| -----	| -----	|  
| Burriss	| 	| The Effect of Social Ties on Mental Health of High School Students in the United States	| Jimmy Chin	|  
| Cecotti	| 	| Impact of constitutional reform on domestic workers in Brazil	| Bill Wang	|  
| Chin	| Nov-28	| Intergenerational Earnings Mobility in China	| 	|  
| Dolder	| Nov-30	| Risk Preferences and Crime	| 	|  
| Li	| 	| Proposing before Match: A New Way to Look at Marriage Matching	| Katie Rha	|  
| Mccallen	| 	| Geopolitical risk and asset prices	| 	|  
| Qiao	| 	| Diffusion of Medical Treatment and Market Competitiveness	| 	|  
| Rha	| Nov-21	| Central bank communication	| 	|  
| Roberts	| 	| The Impact of State-Level Abortion Restrictions on Female Labor Supply	| 	|  
| Saunders	| 	| Price level path targeting	| 	|  
| Suttoni	| 	| Effectiveness of CDFI Loans to Sm all Businesses on Job Growth in the United States	| 	|  
| Wang	| 	| Migrant labor in Singapore	| 	|  
| Xia	| 	| The Short-run Welfare Assessment of Two New Energy Vehicle Policies in China	| 	|  
| Ye	| Nov-28	| REIT Cash Flow Variability and Portfolio Diversification by Property Type	| 	|  

  
