  
## Special dates ## 
  
* Oct-19 (Thu): Fall break 
* Nov-23 (Thu): Thanksgiving 
  
  
## Part I ## 
  
* Aug-22 (Tue): Introduction, [Finding a topic](finding_topic.html) 
* Aug-24 (Thu): TBD 
* Aug-29 (Tue): TBD 
* Aug-31 (Thu): TBD 
* Sep-05 (Tue): TBD 
* Sep-07 (Thu): TBD 
* Sep-12 (Tue): TBD 
* Sep-14 (Thu): TBD 
* Sep-19 (Tue): TBD 
* Sep-21 (Thu): TBD 
* Sep-26 (Tue): TBD 
* Sep-28 (Thu): TBD 
* Oct-03 (Tue): TBD 
* Oct-05 (Thu): TBD 
* Oct-10 (Tue): TBD 
* Oct-12 (Thu): TBD 
* Oct-17 (Tue): TBD 
* Oct-24 (Tue): TBD 
* Oct-26 (Thu): TBD 
* Oct-31 (Tue): TBD 
* Nov-02 (Thu): TBD 
* Nov-07 (Tue): TBD 
* Nov-09 (Thu): TBD 
* Nov-14 (Tue): TBD 
* Nov-16 (Thu): TBD 
* Nov-21 (Tue): TBD 
* Nov-28 (Tue): TBD 
* Nov-30 (Thu): TBD 
* Dec-05 (Tue): TBD 
  
  
## Wrap up ## 
  
* Dec-05 (Tue): Last class 
  
