  
## Regular Class Meetings ## 
  
* Aug-22 (Tue): [Syllabus](syllabus691h.html)
	* [Finding a topic](finding_topic.html),  [Finding an advisor](finding_advisor.html)
	* [Communicating about your thesis](communication.html),  [Useful links](links.html)
* Aug-24 (Thu): 
	* [Finding a topic: examples](finding_topic_examples.html)
	* [Writing a literature review](lit_review.html),  [Reading papers](how_to_read.html)
	* [Working with data](work_with_data.html), [CPS example](cps_earnings.html)
* Aug-29 (Tue): No class. Individual meetings in my office.
* Aug-31 (Thu): No class. Individual meetings in my office.
* Sep-05 (Tue): Presentation by library representative on finding references and data.
	* Bring your laptop.
* Sep-07 (Thu): No class. Individual meetings in my office. 
* Sep-12 (Tue): No class. Individual meetings in my office.

## Mid Semester Presentations

* Sep-14 (Thu): Short presentations on student topics (hopefully; volunteers needed!)
	* Lucas Mccallen
	* You may prepare slides, but are not required to do so.
	* The main purpose is to get feedback on how to sharpen your topic.
* Sep-19 (Tue): No class. Individual meetings in my office. 
* Sep-21 (Thu): No class. Individual meetings in my office.
* Sep-26 (Tue): No class. Individual meetings in my office. 
* Sep-28 (Thu): No class. Individual meetings in my office. 
* Oct-03 (Tue): Student presentations. 
* Oct-05 (Thu): Student presentations.
* Oct-10 (Tue): Student presentations.
* Oct-12 (Thu): Student presentations.
* Oct-17 (Tue): Student presentations.
* Oct-19 (Thu): Fall break 
* Oct-24 (Tue): TBD 
	* Preliminary drafts are due.
* Oct-26 (Thu): TBD 
* Oct-31 (Tue): TBD 


## Final Draft Presentations ##

* Nov-02 (Thu): No class. Individual meetings in my office. 
* Nov-07 (Tue): No class. Individual meetings in my office.
* Nov-09 (Thu): No class. Individual meetings in my office.
* Nov-14 (Tue): Student presentations. 
	* Final drafts are due.
* Nov-16 (Thu): Student presentations.
* Nov-21 (Tue): Student presentations.
* Nov-23 (Thu): Thanksgiving 
* Nov-28 (Tue): Student presentations.
	* Discussions of other student's projects are due.
* Nov-30 (Thu): Student presentations. 
* Dec-05 (Tue): Student presentations. (Last class)
  
