{{../markdown_header.txt}}

# Econ691H - Fall 2017 - Syllabus #

## Objective ##

Students conduct original research under the supervision of faculty members. The end product is an honors thesis.

Students are required to enroll in 691H in the fall and in 692H in the spring. Registration for 692H is automatic for all students enrolled in 691H.

## Organization ##

Class meets Mon, Wed 3:35 - 4:50, GA 307 (but we won't meet often)

Broad outline:

1. Guidance on how to do research. 
2. Students identify broad research areas and pair up with advisors.
3. Advisors help with formulation of precise topics.
2. Students submit drafts at various points in the semester.

A more detailed [schedule](schedule691h.html) is available.

I set up a `slack` to facilitate communication. There, everyone can ask questions, answer questions, or comment on everyone's work.

I recommend bringing a laptop to class.

## Grading ##

Grades are based on:

1. Progress report on topic search and formulation (10%)
	2. due Sep-24
2. Preliminary proposal draft (30%)
	1. due **Oct-22** 
3. Final proposal draft (45%)
	1. due **Nov-19** 
2. Communication with me during the semester (one-on-one meetings and electronic discussions) (15%)

Late submissions receive half credit. Submissions handed in after finals week receive no credit.

Please submit **PDF files only.**

## Progress report 

After the first month, you should have identified a draft topic and done background research on it.

Your report should cover:

1. Rough description of the question or area of your thesis.
2. Sketch of a literature review that identifies where you plan to contribute.

The main purpose is to ensure that you are making progress towards finding a topic and understanding how it fits into the literature.

## Preliminary Proposal Draft ###

By the middle of the fall term, you should have identified a specific topic and done background research on it.

Length: about 5 pages. 

Your proposal should cover:

1. Motivation: what is the question and why is it important?
2. Approach: Roughly how do you plan to answer the question? 
3. Contribution: how does it fit into the literature? What is new?
4. For empirical projects:
	1. Data sources: description and summary statistics for the variables that you plan to use.
	2. Outline the econometric procedures that you plan to use.
5. For theoretical projects:
	1. Sketch the model.
6. Detailed bibliography

## Final Proposal Draft ###

By the end of the semester, you should have produced a detailed outline of your research plans and methods.

The final proposal is structured like the preliminary one, but more detailed and polished. Detailed feedback will be provided by your advisor and by me.

**By the last day of classes**, you should submit a revised draft that addresses these comments.

Length: 15-20 pages.  **PDF files only**.


## Expectations for a Thesis ##

A thesis presents original research. It will typically cover:

1. Introduction
	1. What is the question? Why is it interesting?
	2. How is the question approached? Why is this reasonable?
	3. What are the main findings?
	4. What is the contribution to the literature?
2. Literature review
	1. More details [here](lit_review.html)
3. Outline of empirical methods
	1. What are the challenges to be solved? (E.g., identify cause effect)
	2. What econometric methods are used and why?
	3. What could go wrong? Limitations.
	4. Description of empirical model.
4. Data description
	1. Summary of dataset: coverage, sample design, key variables.
	2. Construction of key variables used in empirical model.
	3. Limitations of the data.
	4. Tables with summary statistics.
5. Results
	1. Discussion of what you find when you estimate your model.
	2. How to interpret the econometric results?
	3. Robustness.
6. Conclusion
	1. A redundant section that rehashes what was written above.

There is no prescribed length. This is entirely dictated by what you need to say. **PDF files only.**

You should provide your computer code with the thesis.

You can find summaries of previous theses [here](material/past_theses_summary.pdf). Examples of successfully completed theses are [here](https://www.dropbox.com/sh/0p766rbip520s3u/AAAy75U8q9ppJ9RNUOPF8kDMa?dl=0).

------------------