{{../markdown_header.txt}}

# Econ691H - Fall 2017 - Syllabus #

## Objective ##

Students conduct original research under the supervision of faculty members. The end product is an honors thesis.

## Organization ##

Class meets Tue, Thr 9:30-10:45 in Gardner 307.

Broad outline:

1. Guidance on how to do research. Lectures and presentations by faculty members.
2. Students identify broad research areas and pair up with advisors.
3. Advisors help with formulation of precise topics.
2. Student presentations of their research projects. Seminar format.

A more detailed [schedule](schedule691h.html) is available.

I set up a `slack` to facilitate communication. There, everyone can ask questions, answer questions, or comment on everyone's work.

I recommend bringing a laptop to class.

## Grading ##

Grades are based on:

1. Class participation (20%)
2. Preliminary proposal draft (25%)
	1. due **Oct-24** 
	2. 20 minute presentation with class discussion
3. Final proposal draft (40%)
	1. due **Nov-14** 
	2. 30 minute presentation with class discussion
4. Detailed discussion of another student's final proposal, due **Nov-28** (15%)

Late submissions receive half credit. Submissions handed in after finals week receive no credit.

## Preliminary Proposal Draft ###

By the middle of the fall term, you should have identified a topic and done background research on it.

Length: about 5 pages.

Your proposal should cover:

1. Motivation: what is the question and why is it important?
2. Approach: Roughly how do you plan to answer the question? 
3. Contribution: how does it fit into the literature? What is new?
4. For empirical projects:
	1. Data sources: description and summary statistics for the variables that you plan to use.
	2. Outline the econometric procedures that you plan to use.
5. For theoretical projects:
	1. Sketch the model.
6. Detailed bibliography

## Final Proposal Draft ###

By the end of the semester, you should have produced a detailed outline of your research plans and methods.

The final proposal is structured like the preliminary one, but more detailed and polished. Detailed feedback will be provided by our advisor and by another student.

**By the last day of classes**, you should submit a revised draft that addresses these comments.

Length: 15-20 pages.



------------------