{{../markdown_header.txt}}

# Econ691H - Fall 2017 - Syllabus #

## Objective ##

Students conduct original research under the supervision of faculty members. The end product is an honors thesis.

Students are required to enroll in 691H in the fall and in 692H in the spring. Registration for 692H is automatic for all students enrolled in 691H.

## Organization ##

Class meets Tue, Thr 9:30-10:45 in Gardner 309.

Broad outline:

1. Guidance on how to do research. 
2. Students identify broad research areas and pair up with advisors.
3. Advisors help with formulation of precise topics.
2. Student presentations of their research projects. Seminar format.

A more detailed [schedule](schedule691h.html) is available.

I set up a `slack` to facilitate communication. There, everyone can ask questions, answer questions, or comment on everyone's work.

I recommend bringing a laptop to class.

## Grading ##

Grades are based on:

1. Class participation (20%)
2. Preliminary proposal draft (25%)
	1. due **Oct-24** 
	2. 20 minute presentation with class discussion
3. Final proposal draft (40%)
	1. due **Nov-14** 
	2. 30 minute presentation with class discussion
4. [Detailed discussion][DiscussionDetails] of another student's final proposal, due **Nov-28** (15%)

Late submissions receive half credit. Submissions handed in after finals week receive no credit.

## Preliminary Proposal Draft ###

By the middle of the fall term, you should have identified a topic and done background research on it.

Length: about 5 pages. **PDF files only.**

Your proposal should cover:

1. Motivation: what is the question and why is it important?
2. Approach: Roughly how do you plan to answer the question? 
3. Contribution: how does it fit into the literature? What is new?
4. For empirical projects:
	1. Data sources: description and summary statistics for the variables that you plan to use.
	2. Outline the econometric procedures that you plan to use.
5. For theoretical projects:
	1. Sketch the model.
6. Detailed bibliography

## Final Proposal Draft ###

By the end of the semester, you should have produced a detailed outline of your research plans and methods.

The final proposal is structured like the preliminary one, but more detailed and polished. Detailed feedback will be provided by our advisor and by another student.

**By the last day of classes**, you should submit a revised draft that addresses these comments.

Length: 15-20 pages.  **PDF files only**.

## Discussion of another student's thesis [DiscussionDetails] ##

Each student submits a critical discussion of another student's final proposal. This will be similar to a referee report for a journal article.

The discussion should cover:

1. Very brief summary of what the thesis does.
2. Is the **question** clear and well motivated? How could it be sharpened?
3. Is the **contribution** relative to the literature clear and significant? How could it be sharpened?
4. Are the **methods** appropriate? How could they be improved?
5. Are the **results** compelling? What could go wrong? How could one address potential objections?

A good discussion is constructive. It points out weaknesses, but also proposes improvements.

There is no prescribed length. However, I expect that the discussant has thought carefully about the thesis.

## Expectations for a Thesis ##

A thesis presents original research. It will typically cover:

1. Introduction
	1. What is the question? Why is it interesting?
	2. How is the question approached? Why is this reasonable?
	3. What are the main findings?
	4. What is the contribution to the literature?
2. Literature review
	1. More details [here](lit_review.html)
3. Outline of empirical methods
	1. What are the challenges to be solved? (E.g., identify cause effect)
	2. What econometric methods are used and why?
	3. What could go wrong? Limitations.
	4. Description of empirical model.
4. Data description
	1. Summary of dataset: coverage, sample design, key variables.
	2. Construction of key variables used in empirical model.
	3. Limitations of the data.
	4. Tables with summary statistics.
5. Results
	1. Discussion of what you find when you estimate your model.
	2. How to interpret the econometric results?
	3. Robustness.
6. Conclusion
	1. A redundant section that rehashes what was written above.

There is no prescribed length. This is entirely dictated by what you need to say. **PDF files only.**

You should provide your computer code with the thesis.

You can find summaries of previous theses [here](material/past_theses_summary.pdf). Examples of successfully completed theses are [here](https://www.dropbox.com/sh/0p766rbip520s3u/AAAy75U8q9ppJ9RNUOPF8kDMa?dl=0).

------------------