{{../markdown_header.txt}}

# Econ692H - Spring - Syllabus #

## Objective ##

This is the second semester in the Economics Honors sequence. Students conduct original research under the supervision of faculty members. The end product is an honors thesis.

Students are required to enroll in 691H in the fall and in 692H in the spring. Registration for 692H is automatic for all students enrolled in 691H.

## Organization ##

I do not expect any class meetings or presentations (other than the thesis defense -- see below). Instead, students will regularly report their progress and receive feedback from their advisor and from myself.

Deadlines:

* March 6: Submit your thesis to your advisor and to me for comments.
* March 20: Respond to comments and resubmit your thesis to your advisor and to me.
* March 26 to April 6: Oral thesis defenses.
* April 9, by noon: Submit your thesis to me. This deadline is set by the Honors office. Do not miss it!
* April 12: [Celebration of undergraduate research](https://our.unc.edu/symposia/cur/), 1:15 to 4:30 p.m.
	* An opportunity to present your research to a wider audience. Please attend!
* April 27, by noon: Submit final version of your thesis electronically to the [Carolina Digital Repository](https://cdr.lib.unc.edu/forms/honors-thesis). Do not miss this deadline or you will not graduate with honors!
	* Email confirmation of submission to me.


Expectations for a Thesis:

* See the [syllabus for Econ691H](syllabus691h.html).
* You should provide your computer code with the thesis.
* More details are [here](http://honorscarolina.unc.edu/research/senior-honors-thesis/).

## Oral thesis defense

You will give a presentation before a committee that includes your advisor and myself (at least). While your advisor makes the final decisions about this, I suggest to aim for about 10 slides.

During the presentation, the committee will ask questions and make suggestions for improvements. Since everyone will know your paper fairly well, I don't expect extensive comments.

Defenses are open for anyone to attend. I encourage all students to sit in on some defenses.

## Grading

Your grade will be entirely based on your thesis and the oral defense.

If you complete the thesis, you will graduate with honors or with highest honors.

If you do not complete your thesis, you must submit a term paper. You will then receive a course grade based on the paper and graduate without honors.

------------------