{{../markdown_header.txt}}

# Possible Topics for Undergraduate Theses #

Disclaimer: These are ideas that I have not investigated in any detail.

## Colleges ##

1. A recent (2017) news report claims that **colleges have become less diverse** in terms of family background. This is measured using the fraction of students receiving Pell Grants (as a proxy for low income). One could use either [HERI](https://heri.ucla.edu/) or [IPEDS](https://nces.ed.gov/ipeds/) data to do better. 
2. The evolution of college student "mismatch."
	Question: How well do college majors match student abilities? How does this change over time?
	Approach: Measure abilities using high school transcripts. Multi-dimensional (such as math, language, reasoning, ...).
	Data: NLSY79 and NLSY97 (may be more, but that's a good start).
	One could also ask: how does college entry / graduation change over time across ability groups?

## Macro Labor ##

1. Why do skill premiums vary across US states? How does it change over time?
	This is very exploratory / uncertain. One would look for an accounting type answer (e.g. industry composition).
2. Could one use variation in state/local income taxes to estimate how much hours worked respond to taxes?
	Major problem: tax rates probably do not vary much over time. Timing of tax changes could be correlated with factors that affect hours worked.
3. Polarization in middle income countries.
	Autor and Dorn document polarization in the US labor market (jobs of intermediate skill intensity disappear). They explore reasons. One could do something similar for middle income countries (BRA, MEX, more?) using IPUMS data.

## Inequality ##

1. Sources of lifetime inequality.
	Question: how important are different income sources for the rich (inheritances, self-employment, capital gains)?
	Background: theories of wealth inequality stress the importance of inheritances and self-employment. Do the data support this?
	Data: PSID.

## Immigrant Earnings ##

1. Variation over time.
	Question: are earnings of immigrants from a given country stable over time? If not: why do they vary (admissions criteria, growth in source country income, ...)?
	Data: IPUMS + US CIS info on admissions by country / year.


-------------