{{../markdown_header.txt}}

# Possible Topics for Undergraduate Theses #

Disclaimer: These are ideas that I have not investigated in any detail.

## Colleges ##

1. A recent (2017) news report claims that **colleges have become less diverse** in terms of family background. This is measured using the fraction of students receiving Pell Grants (as a proxy for low income). One could use either [HERI](https://heri.ucla.edu/) or [IPEDS](https://nces.ed.gov/ipeds/) data to do better. 


-------------