{{markdown_header.txt}}

# The Need for Constitutional Reform #

America elected Trump.

Congress goes along with all manner of [appalling policy proposals](trump_policies.html) made by Trump.

That means the constitution needs to be changed.

The U.S. constitution is 200 years old. It has remained essentially unchanged over the entire period. It does not work any more.

I am not a constitutional scholar, but here is one proposal:

> The president should not be elected directly by the people.

In many countries, voters elect a party. The majority party then chooses a president (or chancellor). This approach prevents a demagogue from coming to power.

Our constitution is not designed to handle a situation where the majority of voters fail to understand basic facts. Now that many voters get their "news" from places like Facebook (perhaps it should be called **Fakebook** instead), an additional layer needs to be placed between the choices of the people and the policies that get implemented.

Other items that seem questionable to me:

1. The president selects the Attorney General, who is then supposed to ensure that the administration follows the law. 
2. Local AG's are elected. This creates obvious conflicts of interest.
3. Judges are elected by voters who don't know anything about them.
4. The president (or governor) can be of a party that holds a minority in both houses of Congress. The obvious result: governance by executive order and gridlock. When this happens, no government appointments can proceed, including Supreme Court justices.

------------