{{markdown_header.txt}}

# Failed COVID response

4/18/2020

The March 2020 stimulus package focuses entirely on "reviving" the economy. What is glaringly missing is a plan to actually get out of the pandemic. Some simple logic:

* We cannot shut everything down until we have a vaccine.
* It is therefore *inevitable* that at least 50 million Americans will get COVID (barring the discovery of a known, safe drug that prevents infection and that can be produced at enormous scale).
* We therefore need a plan that balances slowing the spread of the disease against the economic cost of a shutdown.
* Since no single measure "works", the plan will be a muddling through / compromise where 
	* some people (those who can work from home) will stay isolated for at least a year;
	* some will go back to work, even though it is not safe;
	* hospitals will be overwhelmed for most of the coming 18 months.

What we need right now is therefore obvious: a massive investment in everything that slows the pandemic and in ICU capacity. The stimulus package is entirely missing the ball on this front.

To reopen the economy without incurring tens of millions of deaths, we need testing on a massive scale. The federal government should devote tens of billions of dollars to test production and the development of rapid at home testing. For testing to have impact, every American needs to be tested about once a week. That comes out to 50 million tests a day. This is likely not feasible (but 20 billion dollars solve a lot of problems), but we need to get as close to this as quickly as possible.

But no matter what we do, we will have 50 million+ infections and therefore 5 million+ hospitalizations from COVID. That is about 2% of the population (and it will likely be a lot more). We are therefore hopelessly short of ICU capacity. 

The state of NC has [3,200 ICU beds](https://www.northcarolinahealthnews.org/2020/03/26/covid-19-icu-beds/). With a population of 10 million, we must expect that about 1.5 million will be infected over the next year. About 150,000 of those will need to be hospitalized for about 3 weeks each. That gives about 8,000 ICU patients a day. There will of course be peak times when the number will be far higher. The implication is that NC is needs to increase its ICU capacity (with all associated supplies and personnel) by a factor of at least *5*.

Again, the stimulus bill falls entirely short on that front. These investments needs to be made now to the tune of tens of billions of dollars. Otherwise, the mortality rate from COVID-19 will be far higher than the 1% that some countries achieve.

My prediction is:

* the federal government will do too little far too late
* by the spring of 2021, 100 million Americans will have been infected
* about 10 million of those will have needed hospitalization
* since hospital capacity is only about one quarter of demand, the mortality rate among the 10 million will be high (perhaps 20%)
* **By the spring of 2021, we will see 2 million COVID deaths in the U.S.**

Because of the high mortality, the economy will go back between partial reopening and shutdowns, leading to the largest recession (at least) since the Great Depression.

---------