{{markdown_header.txt}}

This is the personal web page of Lutz Hendricks. My professional page can be found elsewhere. 

# Politics #

* [Poliarization](polarization.html) (2017-April)
* [Hard to Believe but True](hard_to_believe.html)
* [Understanding Republican Policies](republican_strategy.html)
* [Open Letter to Republican Lawmakers](republican_letter.html)
* [The Need for Constitutional Reform](constitutional_reform.html)
* [Predictions for the Trump Presidency](trump_predictions.html) (updated 2017-Aug)
* [Understanding Donald Trump](what_trump_wants.html)
* [Thoughts on the 2016 Presidential Election](trump_voters.html)
* [Repetition Trumps Truth](repetition_truth.html)


---------