{{markdown_header.txt}}


# Repetition Trumps Truth #

How did Trump win the 2016 election?

His campaign was built around one insight:

> When a statement is repeated over and over, people start to believe it. 

> It does not matter whether that statement is true or not. Even if it is easy to prove that a statement is false, that's ok.

> Repetition trumps truth.

Example: The Trump tax proposal.

* Trump claimed again and again that there will be big tax cuts on the middle class. 
* At the same time, he put out a tax proposal (one of very few actual policy proposals of his campaign) that cut taxes on the rich, but raised taxes on the middle class.
* Voters believed the rhetoric.

The tax plan illustrates another clever strategy that was employed many times in Trump's campaign.

> It is possible to say two opposing things at the same time. Then voters can choose to believe what they want.

In the tax case: informed voters (typically higher income) rationally chose to believe in the tax plan. Uninformed voters (typically lower income) were ignorant of the plan and believed the rhetoric.

This is, of course, a disaster for democracy. The next president won the election by simply repeating wrong claims (with just a grain of truth in them, so they don't sound absurd). 

He demonstrated a winning strategy:

1. Keep the eyeballs trained on yourself, so you can control the media cycle. 
2. If this takes extreme statements, so be it. One can always walk them back later. In fact, *outrageous statements are great*. Voters who find the distasteful can choose to interpret them as campaign rhetoric. Extreme voters can choose to take them at face value. Everyone gets what they want to believe.
2. Invent negative news about your opponent and just *keep repeating* them. The trick is to have something new to say every few days to keep the spotlight on the opponent. But this is not too hard, if you can simply invent the news.

Clinton effectively lost the election because she ran a private email server as Secretary of State. By any reasonable standard, this is a minor issue. But it opened the door to Trump's strategy of repeating bad news about his opponent. Of course, he did have some help from Wikileaks and James Comy.

What now?

-----------