{{markdown_header.txt}}

# Interpreting Trump #

Many observers ask: 

> What are Trump's policy plans? What does he want to achieve?

I think these questions fail to understand Trump.

I view all of Trump's actions as part of his re-election campaign. He will do whatever makes him popular. 

### Examples ###

1. The executive order on Obamacare, signed on his first day in office.

	The executive order is so vague, it's essentially a statement of broad intent. What then is the point? Trump sets himself up to say: "I kept my promise and repealed Obamacare on my first day in office."
	
	In reality, I expect that the repeal of Obamacare will be mainly cosmetic ("repeal and rename"). Actually changing Obamacare substantively would be highly unpopular. There is, of course, no plan to cover more people at lower cost. If there were, we would have probably seen some form of public discussion / bragging about it. So the optimal action is to do just enough so Trump can claim that Obamacare has been repealed and is now so much better.

2. The inauguration speech

	Why this description of America in the dumpster? Quite a bit of it is hard to support with facts. Notably, the economy is doing rather well, except that inequality is extremely high.

	The answer is obvious once one views this as a campaign speech. Trump is setting himself up to be able to say: "Look how awful everything was when I took over. Now it is so much better."

--------